/**
 * Intelligence Versioning (P0-B Workstream 8).
 *
 * Every Product Intelligence update receives permanent history:
 * Version · Timestamp · Reason · Author · Generated by · Human approved · Delta summary
 */

import type {
  ProductIntelligenceId,
  ProductIntelligenceObjectType,
} from "./primitives";

export type IntelligenceGeneratedBy = "human" | "agent" | "system";

/**
 * Permanent version record for any Product Intelligence mutation.
 */
export interface IntelligenceVersionRecord {
  /** Monotonic or semver-like version for the object (e.g. "1.0.0"). */
  version: string;
  /** ISO-8601 timestamp. */
  timestamp: string;
  /** Why this update occurred. */
  reason: string;
  /** Human author identity or role label. */
  author: string;
  /** Who/what produced the change payload. */
  generatedBy: IntelligenceGeneratedBy;
  /** Agent/system identifier when generatedBy is not human. */
  generatedById: string | null;
  /** Whether a human approved this version. */
  humanApproved: boolean;
  /** Approver identity when humanApproved is true. */
  approvedBy: string | null;
  /** Concise structured delta — not an essay. */
  deltaSummary: string;
  /** Object this version belongs to. */
  objectId: ProductIntelligenceId;
  objectType: ProductIntelligenceObjectType;
  /** Prior version string, or null for first version. */
  previousVersion: string | null;
}

export interface IntelligenceVersionHistory {
  schemaVersion: "P0-B";
  /** Append-only history. Empty in P0-B (contracts only). */
  records: IntelligenceVersionRecord[];
}

export function createEmptyVersionHistory(): IntelligenceVersionHistory {
  return {
    schemaVersion: "P0-B",
    records: [],
  };
}

/**
 * Construct a version record. Does not persist — persistence comes in later batches.
 */
export function createVersionRecord(input: {
  version: string;
  timestamp: string;
  reason: string;
  author: string;
  generatedBy: IntelligenceGeneratedBy;
  generatedById?: string | null;
  humanApproved: boolean;
  approvedBy?: string | null;
  deltaSummary: string;
  objectId: ProductIntelligenceId;
  objectType: ProductIntelligenceObjectType;
  previousVersion?: string | null;
}): IntelligenceVersionRecord {
  if (input.humanApproved && !input.approvedBy) {
    throw new Error(
      "IntelligenceVersionRecord with humanApproved=true requires approvedBy.",
    );
  }
  return {
    version: input.version,
    timestamp: input.timestamp,
    reason: input.reason,
    author: input.author,
    generatedBy: input.generatedBy,
    generatedById: input.generatedById ?? null,
    humanApproved: input.humanApproved,
    approvedBy: input.approvedBy ?? null,
    deltaSummary: input.deltaSummary,
    objectId: input.objectId,
    objectType: input.objectType,
    previousVersion: input.previousVersion ?? null,
  };
}
