export const CLIENT_LOGOS = [
  { name: "Primal Motorsports", src: "/migrated-assets/logos/primal.svg" },
  { name: "Cusick Morgan", src: "/migrated-assets/logos/cusick-morgan.svg" },
  { name: "Plate the Umpqua", src: "/migrated-assets/logos/plate-the-umpqua.svg" },
  { name: "SBE", src: "/migrated-assets/logos/sbe.svg" },
  { name: "OTP", src: "/migrated-assets/logos/otp.svg" },
  { name: "Dialed In Electric", src: "/migrated-assets/logos/dialed-in-electric.svg" },
  { name: "Democratic Club", src: "/migrated-assets/logos/the-democratic.svg" },
  { name: "Golden State Warriors", src: "/migrated-assets/logos/golden-state.svg" },
  { name: "Bobby-Q Mesa", src: "/migrated-assets/logos/bobby-q.svg" },
  { name: "Hair Mafia", src: "/migrated-assets/logos/hair-mafia.svg" },
  { name: "Indivisible", src: "/migrated-assets/logos/indivisible.svg" },
  { name: "James Kali Financial", src: "/migrated-assets/logos/james-kali.svg" },
  { name: "La Lola", src: "/migrated-assets/logos/lalola.svg" },
  { name: "LeadsRabbit", src: "/migrated-assets/logos/leadsrabbit.svg" },
  { name: "10 Summers", src: "/migrated-assets/logos/10-summer.svg" },
  { name: "Gaya Palmer", src: "/migrated-assets/logos/gaya-palmer.svg" },
  { name: "SHVO", src: "/migrated-assets/logos/shvo.svg" },
  { name: "AutoDV8ions", src: "/migrated-assets/logos/dv8.svg" },
] as const;
