export const HOMEPAGE_SERVICES = [
  {
    number: "01",
    title: "Luxury Website Experiences",
    slug: "luxury-website-experiences",
    forWho: "Brands that need to look expensive before they say a word.",
    creates:
      "Design systems, conversion paths, content hierarchy, and launch-ready web presence.",
    whyMatters: "Your website is the first proof of standard.",
    summary:
      "Custom websites built to hold weight from the first impression to the final conversion path.",
    primary: true,
    icon: "layers" as const,
    cta: "Explore Service" as const,
  },
  {
    number: "02",
    title: "Brand Systems & Identity",
    slug: "brand-systems-identity",
    forWho: "Teams aligning voice, visuals, and positioning before a major build.",
    creates: "Identity systems and visual direction that stay coherent.",
    whyMatters: "Without a system, every page fights the last one.",
    summary: "Voice, visuals, and positioning — aligned with discipline.",
    primary: false,
    icon: "shapes" as const,
    cta: "View Fit" as const,
  },
  {
    number: "03",
    title: "Growth Infrastructure",
    slug: "growth-infrastructure",
    forWho: "Brands with traffic that needs structure and measurement.",
    creates: "SEO, analytics, and lead systems wired to outcomes.",
    whyMatters: "Traffic without structure is noise.",
    summary: "SEO, analytics, and lead systems that compound.",
    primary: false,
    icon: "chart" as const,
    cta: "View Fit" as const,
  },
  {
    number: "04",
    title: "Enterprise Platforms & Operational Systems",
    slug: "enterprise-platforms",
    forWho: "Organizations that have outgrown disconnected tools.",
    creates: "Client portals and operational platforms built around your workflow.",
    whyMatters: "When the website is not enough, we build what your team runs on.",
    summary: "Portals and platforms built for how you work.",
    primary: false,
    icon: "grid" as const,
    cta: "Start a Project" as const,
  },
] as const;
