import type { PlaybookTemplate } from "./types";

function steps(
  items: Array<{ title: string; desc?: string; module?: string; trigger?: PlaybookTemplate["steps"][0]["automationTrigger"]; min?: number }>,
): PlaybookTemplate["steps"] {
  return items.map((item, i) => ({
    order: i + 1,
    title: item.title,
    description: item.desc,
    linkedModule: item.module,
    automationTrigger: item.trigger ?? "none",
    estimatedMinutes: item.min ?? 15,
    required: true,
  }));
}

export const BUILTIN_PLAYBOOK_TEMPLATES: PlaybookTemplate[] = [
  {
    slug: "website-launch",
    name: "Website Launch",
    description: "End-to-end website launch from final QA through DNS cutover and client handoff.",
    category: "launch",
    icon: "WL",
    color: "gold",
    estimatedDuration: "2–5 days",
    appliesTo: ["client", "website", "project"],
    tags: ["launch", "website"],
    steps: steps([
      { title: "Staging sign-off", desc: "Confirm client approval on staging", module: "Projects" },
      { title: "Final QA pass", desc: "Mobile, forms, tracking, performance — complete Launch QA checklist", module: "Projects", trigger: "run_website_audit" },
      { title: "DNS & SSL prep", desc: "Records documented and validated", module: "Infrastructure" },
      { title: "Launch window scheduled", desc: "Align with client on go-live", module: "Timeline", trigger: "schedule_meeting" },
      { title: "Production smoke test", module: "Projects" },
      { title: "Launch confirmation", desc: "Client handoff email and portal", module: "Portal", trigger: "send_portal_invite" },
    ]),
  },
  {
    slug: "client-onboarding",
    name: "Client Onboarding",
    description: "Structured onboarding from contract to active delivery and portal access.",
    category: "onboarding",
    icon: "OB",
    estimatedDuration: "1–2 weeks",
    appliesTo: ["client", "agency"],
    steps: steps([
      { title: "Kickoff scheduled", module: "Timeline", trigger: "schedule_meeting" },
      { title: "Portal provisioned", module: "Portal", trigger: "send_portal_invite" },
      { title: "Brand assets collected", module: "Creative" },
      { title: "Retainer & billing confirmed", module: "Sales" },
      { title: "First deliverable planned", module: "Projects", trigger: "create_deliverable" },
      { title: "Onboarding approved", module: "Onboarding", trigger: "launch_client" },
    ]),
  },
  {
    slug: "seo-launch",
    name: "SEO Launch",
    description: "Technical SEO foundation at launch — analytics, indexing, and on-page baseline.",
    category: "seo",
    icon: "SEO",
    estimatedDuration: "3–7 days",
    appliesTo: ["website", "client"],
    steps: steps([
      { title: "GA4 & GTM verified", module: "Infrastructure" },
      { title: "Search Console connected", module: "Infrastructure" },
      { title: "Sitemap submitted", module: "Infrastructure" },
      { title: "On-page SEO baseline", module: "Projects" },
      { title: "Local SEO checklist", module: "Infrastructure" },
      { title: "SEO launch sign-off", module: "Reporting" },
    ]),
  },
  {
    slug: "monthly-retainer",
    name: "Monthly Retainer",
    description: "Monthly rhythm for retainer clients — scope, delivery, and relationship health.",
    category: "operations",
    icon: "MR",
    estimatedDuration: "Monthly",
    appliesTo: ["client", "agency"],
    steps: steps([
      { title: "Review open requests", module: "Projects", trigger: "create_request" },
      { title: "Confirm deliverable queue", module: "Projects", trigger: "create_deliverable" },
      { title: "Billing & retainer check", module: "Sales" },
      { title: "Client health update", module: "Strategy Vault", trigger: "create_executive_note" },
      { title: "Next month plan", module: "Strategy Vault" },
    ]),
  },
  {
    slug: "monthly-reporting",
    name: "Monthly Reporting",
    description: "Generate, review, and publish the monthly executive report.",
    category: "reporting",
    icon: "RP",
    estimatedDuration: "2–4 hours",
    appliesTo: ["client"],
    steps: steps([
      { title: "Gather monthly metrics", module: "Reporting" },
      { title: "Generate report draft", module: "Reporting", trigger: "generate_report" },
      { title: "Internal review", module: "Reporting" },
      { title: "Publish to portal", module: "Reporting" },
      { title: "Notify client", module: "Portal" },
    ]),
  },
  {
    slug: "proposal-conversion",
    name: "Proposal Conversion",
    description: "Move a proposal from sent to signed and onboarded.",
    category: "sales",
    icon: "PC",
    estimatedDuration: "1–3 weeks",
    appliesTo: ["client"],
    steps: steps([
      { title: "Proposal sent", module: "Sales", trigger: "generate_proposal" },
      { title: "Follow-up touchpoint", module: "Timeline", trigger: "schedule_meeting" },
      { title: "Proposal approved", module: "Sales" },
      { title: "Contract & payment", module: "Sales" },
      { title: "Launch onboarding", module: "Onboarding", trigger: "launch_client" },
    ]),
  },
  {
    slug: "website-audit",
    name: "Website Audit",
    description: "Run a comprehensive website audit and deliver findings.",
    category: "audit",
    icon: "AU",
    estimatedDuration: "1–2 days",
    appliesTo: ["website", "client"],
    steps: steps([
      { title: "Run automated audit", module: "Infrastructure", trigger: "run_website_audit" },
      { title: "Manual QA review", module: "Projects" },
      { title: "Prioritize findings", module: "Strategy Vault" },
      { title: "Executive summary note", module: "Strategy Vault", trigger: "create_executive_note" },
      { title: "Share with client", module: "Portal" },
    ]),
  },
  {
    slug: "brand-discovery",
    name: "Brand Discovery",
    description: "Discovery session and brand direction capture for new creative work.",
    category: "strategy",
    icon: "BD",
    estimatedDuration: "1 week",
    appliesTo: ["client", "campaign"],
    steps: steps([
      { title: "Discovery call", module: "Timeline", trigger: "schedule_meeting" },
      { title: "Capture strategy notes", module: "Strategy Vault", trigger: "create_executive_note" },
      { title: "Brand kit draft", module: "Creative" },
      { title: "Direction approval", module: "Creative" },
    ]),
  },
  {
    slug: "campaign-launch",
    name: "Campaign Launch",
    description: "Launch a creative campaign across assets and channels.",
    category: "launch",
    icon: "CM",
    estimatedDuration: "1–2 weeks",
    appliesTo: ["campaign", "client"],
    steps: steps([
      { title: "Campaign brief locked", module: "Creative" },
      { title: "Assets in production", module: "Creative", trigger: "create_deliverable" },
      { title: "Internal QA", module: "Creative" },
      { title: "Client approval", module: "Creative" },
      { title: "Go live", module: "Creative" },
    ]),
  },
  {
    slug: "motorsports-client-launch",
    name: "Motorsports Client Launch",
    description: "Vertical launch playbook for motorsports clients — events, media, and sponsorship rhythm.",
    category: "vertical",
    icon: "MS",
    estimatedDuration: "2–4 weeks",
    appliesTo: ["motorsports", "client"],
    steps: steps([
      { title: "Season calendar intake", module: "Strategy Vault" },
      { title: "Event content plan", module: "Creative", trigger: "create_deliverable" },
      { title: "Sponsor asset checklist", module: "Creative" },
      { title: "Website & social alignment", module: "Projects" },
      { title: "Launch announcement", module: "Timeline" },
    ]),
  },
  {
    slug: "contractor-launch",
    name: "Contractor Launch",
    description: "Launch playbook for contractor vertical — trust, service areas, and lead capture.",
    category: "vertical",
    icon: "CT",
    estimatedDuration: "2–3 weeks",
    appliesTo: ["contractor", "client"],
    steps: steps([
      { title: "Service area & licensing review", module: "Strategy Vault" },
      { title: "Lead capture forms QA", module: "Projects" },
      { title: "GBP & local SEO", module: "Infrastructure" },
      { title: "Portfolio & case studies live", module: "Projects" },
      { title: "Go-live review", module: "Reporting" },
    ]),
  },
  {
    slug: "hospitality-launch",
    name: "Hospitality Launch",
    description: "Launch playbook for hospitality — reservations, menus, and experience marketing.",
    category: "vertical",
    icon: "HO",
    estimatedDuration: "2–3 weeks",
    appliesTo: ["hospitality", "client"],
    steps: steps([
      { title: "Menu & hours content", module: "Projects" },
      { title: "Reservation & booking links", module: "Projects" },
      { title: "Photography & hero assets", module: "Creative" },
      { title: "GBP optimization", module: "Infrastructure" },
      { title: "Soft launch review", module: "Reporting" },
    ]),
  },
  {
    slug: "executive-strategy-session",
    name: "Executive Strategy Session",
    description: "Prepare and run an executive strategy session with the client.",
    category: "strategy",
    icon: "ES",
    estimatedDuration: "1 week",
    appliesTo: ["client", "agency"],
    steps: steps([
      { title: "Pre-read assembled", module: "Strategy Vault" },
      { title: "Agenda sent", module: "Timeline", trigger: "schedule_meeting" },
      { title: "Session held", module: "Timeline" },
      { title: "Decisions captured", module: "Strategy Vault", trigger: "create_executive_note" },
      { title: "Follow-up actions assigned", module: "Projects", trigger: "create_request" },
    ]),
  },
  {
    slug: "quarterly-business-review",
    name: "Quarterly Business Review",
    description: "Quarterly business review — performance, roadmap, and growth planning.",
    category: "strategy",
    icon: "QBR",
    estimatedDuration: "Quarterly",
    appliesTo: ["client", "agency"],
    steps: steps([
      { title: "Quarter metrics compiled", module: "Reporting", trigger: "generate_report" },
      { title: "QBR deck prepared", module: "Reporting" },
      { title: "Review meeting scheduled", module: "Timeline", trigger: "schedule_meeting" },
      { title: "QBR conducted", module: "Timeline" },
      { title: "Next quarter plan logged", module: "Strategy Vault", trigger: "create_executive_note" },
    ]),
  },
  {
    slug: "annual-website-review",
    name: "Annual Website Review",
    description: "Annual comprehensive website and infrastructure review.",
    category: "audit",
    icon: "AW",
    estimatedDuration: "Annual",
    appliesTo: ["website", "client"],
    steps: steps([
      { title: "Full site audit", module: "Infrastructure", trigger: "run_website_audit" },
      { title: "Infrastructure registry review", module: "Infrastructure" },
      { title: "Content & SEO refresh plan", module: "Strategy Vault" },
      { title: "Annual review meeting", module: "Timeline", trigger: "schedule_meeting" },
      { title: "Roadmap approved", module: "Strategy Vault", trigger: "create_executive_note" },
    ]),
  },
];

export const QUICK_LAUNCH_SLUGS = {
  websiteLaunch: "website-launch",
  monthlyReport: "monthly-reporting",
  onboarding: "client-onboarding",
  quarterlyReview: "quarterly-business-review",
  seoChecklist: "seo-launch",
  websiteAudit: "website-audit",
} as const;
