import type {
  PlatformMeta,
  PlatformPhaseDefinition,
  PlatformPrinciple,
  PlatformSubsystemDefinition,
} from "./types";

/** Single source of truth — update per platform phase completion. */
export const PLATFORM_META: Omit<PlatformMeta, "buildDate"> = {
  currentPhase: "12A.2",
  currentPhaseTitle: "KXD Work Items Foundation",
  version: "0.1.0",
  editionLabel: "KXD Core (Edition 1)",
};

export const PLATFORM_PRINCIPLES: PlatformPrinciple[] = [
  { id: "friction", text: "Reduce operational friction." },
  { id: "automation", text: "Increase automation." },
  { id: "clarity", text: "Increase clarity." },
  { id: "reuse", text: "Build reusable systems." },
  { id: "simplicity", text: "Avoid unnecessary complexity." },
  { id: "edition", text: "KXD Agency is Edition 1." },
  { id: "purpose", text: "Every feature must have a purpose." },
];

export const PLATFORM_PHASES: PlatformPhaseDefinition[] = [
  {
    id: "phase-6b",
    number: "6B",
    title: "Executive Dashboard",
    status: "completed",
    description: "Portfolio KPI aggregation, action center, and widget host for leadership briefing.",
    completedAt: "2025-12-01",
  },
  {
    id: "phase-8a",
    number: "8A",
    title: "Edition Framework",
    status: "completed",
    description: "Edition registry, module gating, branding, and navigation filtering for future SaaS evolution.",
    completedAt: "2026-02-01",
  },
  {
    id: "phase-10a",
    number: "10A",
    title: "Performance Reports",
    status: "completed",
    description: "Executive performance reporting extended through monthly-reports and lib/reporting.",
    completedAt: "2026-06-01",
  },
  {
    id: "phase-11a",
    number: "11A",
    title: "Architecture Assessment",
    status: "completed",
    description: "Full engineering architecture assessment of KXD OS before platform evolution.",
    completedAt: "2026-06-15",
  },
  {
    id: "phase-11b",
    number: "11B",
    title: "Platform Language Map",
    status: "completed",
    description: "Engineering naming and classification map for SaaS evolution — keep, abstract, rename guidance.",
    completedAt: "2026-06-20",
  },
  {
    id: "phase-11c",
    number: "11C",
    title: "Platform Boundary Inventory",
    status: "completed",
    description: "Subsystem-by-subsystem boundary inventory, dependency map, maturity assessment, and build priorities.",
    completedAt: "2026-06-25",
  },
  {
    id: "phase-11d",
    number: "11D",
    title: "Platform Progress Dashboard",
    status: "completed",
    description: "Internal engineering cockpit — platform completion, subsystem maturity, roadmap, and health metrics.",
    completedAt: "2026-07-06",
  },
  {
    id: "phase-12a2",
    number: "12A.2",
    title: "KXD Work Items Foundation",
    status: "completed",
    description: "Work Items facade, schema extensions, Activity Engine hooks, Client Command Work tab, portal request spawning.",
    completedAt: "2026-07-06",
  },
  {
    id: "phase-12",
    number: "12",
    title: "Timeline Unification",
    status: "planned",
    description: "Retire legacy client-timeline-events writes; enforce Activity Engine as sole timeline ingress.",
  },
  {
    id: "phase-13",
    number: "13",
    title: "Workspace Consolidation",
    status: "planned",
    description: "Make Client Command canonical; consolidate or redirect Executive Client Workspace.",
  },
  {
    id: "phase-14",
    number: "14",
    title: "Automation Module Connection",
    status: "planned",
    description: "Wire Creative, Requests, Deliverables, and Portal to automation publishers.",
  },
  {
    id: "phase-15",
    number: "15",
    title: "Intelligence Performance",
    status: "planned",
    description: "Incremental context loading, per-client cache, and materialized health scores.",
  },
  {
    id: "phase-16",
    number: "16",
    title: "Live Analytics Completion",
    status: "planned",
    description: "GA4 and Search Console feeds into reporting metrics and portal analytics modules.",
  },
  {
    id: "phase-17",
    number: "17",
    title: "Lead Funnel Unification",
    status: "planned",
    description: "Normalize research-leads, sales-leads, and website-audits into a shared pipeline model.",
  },
];

/** Subsystem registry — sourced from Phase 11C boundary inventory. */
export const PLATFORM_SUBSYSTEMS: PlatformSubsystemDefinition[] = [
  {
    id: "editions",
    name: "Editions",
    category: "Platform",
    owner: "platform-owner",
    maturity: "alpha",
    completionPercent: 48,
    status: "active",
    dependencies: [],
    lastCompletedPhase: "11C",
    currentPhase: "11D",
    description: "Edition registry and module gating for future SaaS.",
  },
  {
    id: "activity-engine",
    name: "Activity Engine",
    category: "Operations",
    owner: "shared-core",
    maturity: "beta",
    completionPercent: 82,
    status: "active",
    dependencies: ["Timeline", "Intelligence"],
    lastCompletedPhase: "12A.2",
    currentPhase: "12",
    href: "/admin/operations/client-command/backfill",
    description: "Canonical client activity publishing with dedupe.",
  },
  {
    id: "timeline",
    name: "Timeline",
    category: "Operations",
    owner: "shared-core",
    maturity: "beta",
    completionPercent: 70,
    status: "consolidation",
    dependencies: ["Activity Engine"],
    lastCompletedPhase: "11C",
    currentPhase: "12",
    href: "/admin/operations/timeline",
    description: "Executive relationship history — portfolio and per-client views.",
  },
  {
    id: "communications",
    name: "Communications",
    category: "Client Ops",
    owner: "shared-core",
    maturity: "beta",
    completionPercent: 78,
    status: "stable",
    dependencies: ["Activity Engine", "Client Command"],
    lastCompletedPhase: "11C",
    currentPhase: "—",
    href: "/admin/operations/client-command",
  },
  {
    id: "client-actions",
    name: "Client Actions",
    category: "Client Ops",
    owner: "shared-core",
    maturity: "beta",
    completionPercent: 76,
    status: "stable",
    dependencies: ["Activity Engine", "Intelligence"],
    lastCompletedPhase: "11C",
    currentPhase: "—",
    href: "/admin/operations/client-command",
  },
  {
    id: "client-command",
    name: "Client Command",
    category: "Client Ops",
    owner: "shared-core",
    maturity: "production",
    completionPercent: 95,
    status: "stable",
    dependencies: ["Intelligence", "Financial Command", "Timeline"],
    lastCompletedPhase: "11C",
    currentPhase: "13",
    href: "/admin/operations/client-command",
    description: "Primary per-client operational HQ.",
  },
  {
    id: "client-workspace",
    name: "Client Workspace",
    category: "Client Ops",
    owner: "shared-core",
    maturity: "alpha",
    completionPercent: 42,
    status: "consolidation",
    dependencies: ["Client Command"],
    lastCompletedPhase: "11C",
    currentPhase: "13",
    href: "/admin/operations/clients",
    description: "Parallel executive workspace — consolidation planned.",
  },
  {
    id: "executive-dashboard",
    name: "Executive Dashboard",
    category: "Leadership",
    owner: "shared-core",
    maturity: "production",
    completionPercent: 94,
    status: "stable",
    dependencies: ["Intelligence", "Financial Command", "Sales"],
    lastCompletedPhase: "10A",
    currentPhase: "—",
    href: "/admin/operations/executive",
  },
  {
    id: "reporting",
    name: "Reporting",
    category: "Intelligence",
    owner: "shared-core",
    maturity: "beta",
    completionPercent: 80,
    status: "active",
    dependencies: ["Intelligence", "Live Integrations"],
    lastCompletedPhase: "10A",
    currentPhase: "16",
    href: "/admin/operations/reports",
  },
  {
    id: "financial-command",
    name: "Financial Command",
    category: "Finance",
    owner: "shared-core",
    maturity: "beta",
    completionPercent: 75,
    status: "stable",
    dependencies: ["Sales", "Contracts"],
    lastCompletedPhase: "11C",
    currentPhase: "—",
    href: "/admin/operations/accounts",
  },
  {
    id: "proposal-system",
    name: "Proposal System",
    category: "Sales",
    owner: "shared-core",
    maturity: "production",
    completionPercent: 90,
    status: "stable",
    dependencies: ["Sales", "Contracts", "Client Launch"],
    lastCompletedPhase: "11C",
    currentPhase: "17",
    href: "/admin/sales/proposals",
  },
  {
    id: "sales",
    name: "Sales",
    category: "Sales",
    owner: "shared-core",
    maturity: "production",
    completionPercent: 93,
    status: "stable",
    dependencies: ["Proposal System"],
    lastCompletedPhase: "11C",
    currentPhase: "17",
    href: "/admin/sales",
  },
  {
    id: "contracts",
    name: "Contracts",
    category: "Sales",
    owner: "shared-core",
    maturity: "beta",
    completionPercent: 74,
    status: "stable",
    dependencies: ["Sales", "Financial Command"],
    lastCompletedPhase: "11C",
    currentPhase: "—",
    href: "/admin/operations/client-command",
  },
  {
    id: "intelligence",
    name: "Intelligence",
    category: "Intelligence",
    owner: "shared-core",
    maturity: "production",
    completionPercent: 96,
    status: "stable",
    dependencies: [],
    lastCompletedPhase: "11C",
    currentPhase: "15",
    href: "/admin/operations/founder-intelligence",
    description: "Deterministic portfolio context and recommendations.",
  },
  {
    id: "brain",
    name: "Brain",
    category: "Intelligence",
    owner: "shared-core",
    maturity: "beta",
    completionPercent: 78,
    status: "active",
    dependencies: ["Intelligence", "Automation", "Live Integrations"],
    lastCompletedPhase: "11C",
    currentPhase: "15",
    href: "/admin/operations/brain",
  },
  {
    id: "search",
    name: "Search",
    category: "Platform",
    owner: "shared-core",
    maturity: "production",
    completionPercent: 94,
    status: "stable",
    dependencies: ["Intelligence", "Editions"],
    lastCompletedPhase: "11C",
    currentPhase: "—",
  },
  {
    id: "notifications",
    name: "Notifications",
    category: "Platform",
    owner: "shared-core",
    maturity: "beta",
    completionPercent: 68,
    status: "stable",
    dependencies: ["Automation"],
    lastCompletedPhase: "11C",
    currentPhase: "14",
  },
  {
    id: "automation",
    name: "Automation",
    category: "Platform",
    owner: "platform-owner",
    maturity: "beta",
    completionPercent: 72,
    status: "active",
    dependencies: ["Timeline", "Notifications"],
    lastCompletedPhase: "11C",
    currentPhase: "14",
    href: "/admin/operations/automation",
  },
  {
    id: "portal",
    name: "Portal",
    category: "Client Experience",
    owner: "shared-core",
    maturity: "beta",
    completionPercent: 76,
    status: "active",
    dependencies: ["Reporting", "Financial Command", "Editions"],
    lastCompletedPhase: "11C",
    currentPhase: "16",
    href: "/portal",
    description: "Client HQ — core modules live; analytics and advisor scaffolded.",
  },
  {
    id: "client-onboarding",
    name: "Client Onboarding",
    category: "Client Ops",
    owner: "shared-core",
    maturity: "production",
    completionPercent: 91,
    status: "stable",
    dependencies: ["Automation", "Portal"],
    lastCompletedPhase: "11C",
    currentPhase: "—",
    href: "/admin/operations/onboarding",
  },
  {
    id: "client-success",
    name: "Client Success",
    category: "Client Ops",
    owner: "shared-core",
    maturity: "alpha",
    completionPercent: 50,
    status: "planned",
    dependencies: ["Intelligence", "Automation"],
    lastCompletedPhase: "11C",
    currentPhase: "—",
    href: "/admin/operations/client-success",
  },
  {
    id: "infrastructure",
    name: "Infrastructure",
    category: "Operations",
    owner: "shared-core",
    maturity: "beta",
    completionPercent: 77,
    status: "stable",
    dependencies: ["Live Integrations"],
    lastCompletedPhase: "11C",
    currentPhase: "—",
    href: "/admin/operations/infrastructure",
  },
  {
    id: "website-auditor",
    name: "Website Auditor",
    category: "Growth",
    owner: "agency-edition",
    maturity: "production",
    completionPercent: 92,
    status: "stable",
    dependencies: ["Automation", "Sales"],
    lastCompletedPhase: "11C",
    currentPhase: "17",
    href: "/admin/operations/audits",
  },
  {
    id: "creative",
    name: "Creative Engine",
    category: "Studio",
    owner: "agency-edition",
    maturity: "beta",
    completionPercent: 74,
    status: "active",
    dependencies: ["Integrations"],
    lastCompletedPhase: "11C",
    currentPhase: "14",
    href: "/admin/operations/creative",
  },
  {
    id: "junior-creators",
    name: "Junior Creators",
    category: "Studio",
    owner: "agency-edition",
    maturity: "beta",
    completionPercent: 72,
    status: "stable",
    dependencies: ["Research"],
    lastCompletedPhase: "11C",
    currentPhase: "—",
    href: "/admin/operations/junior-creators",
  },
  {
    id: "research",
    name: "Research Leads",
    category: "Growth",
    owner: "agency-edition",
    maturity: "alpha",
    completionPercent: 46,
    status: "consolidation",
    dependencies: ["Sales"],
    lastCompletedPhase: "11C",
    currentPhase: "17",
    href: "/admin/operations/research",
  },
  {
    id: "playbooks",
    name: "Playbooks",
    category: "Operations",
    owner: "shared-core",
    maturity: "beta",
    completionPercent: 75,
    status: "stable",
    dependencies: ["Automation", "Timeline"],
    lastCompletedPhase: "11C",
    currentPhase: "—",
    href: "/admin/operations/playbooks",
  },
  {
    id: "genesis",
    name: "Genesis",
    category: "Client Ops",
    owner: "shared-core",
    maturity: "beta",
    completionPercent: 78,
    status: "stable",
    dependencies: ["Client Onboarding", "Playbooks"],
    lastCompletedPhase: "11C",
    currentPhase: "—",
    href: "/admin/operations/genesis",
  },
  {
    id: "launch-qa",
    name: "Launch QA",
    category: "Operations",
    owner: "shared-core",
    maturity: "beta",
    completionPercent: 76,
    status: "stable",
    dependencies: ["Live Integrations", "Playbooks"],
    lastCompletedPhase: "11C",
    currentPhase: "—",
    href: "/admin/operations/launch-qa",
  },
  {
    id: "integrations",
    name: "Integrations",
    category: "Platform",
    owner: "platform-owner",
    maturity: "beta",
    completionPercent: 73,
    status: "active",
    dependencies: [],
    lastCompletedPhase: "11C",
    currentPhase: "16",
    href: "/admin/operations/integrations",
  },
  {
    id: "live-integrations",
    name: "Live Integrations",
    category: "Platform",
    owner: "platform-owner",
    maturity: "beta",
    completionPercent: 68,
    status: "active",
    dependencies: ["Integrations", "Brain"],
    lastCompletedPhase: "11C",
    currentPhase: "16",
    href: "/admin/operations/integrations",
  },
];
