import type {
  PlatformMeta,
  PlatformPhaseDefinition,
  PlatformPrinciple,
  PlatformSubsystemDefinition,
} from "./types";

/** Single source of truth — update per platform phase completion. */
export const PLATFORM_META: Omit<PlatformMeta, "buildDate"> = {
  currentPhase: "12A.2",
  currentPhaseTitle: "KXD Work Items Foundation",
  version: "0.1.0",
  editionLabel: "KXD Core (Edition 1)",
};

export const PLATFORM_PRINCIPLES: PlatformPrinciple[] = [
  { id: "friction", text: "Reduce operational friction." },
  { id: "automation", text: "Increase automation." },
  { id: "clarity", text: "Increase clarity." },
  { id: "reuse", text: "Build reusable systems." },
  { id: "simplicity", text: "Avoid unnecessary complexity." },
  { id: "edition", text: "KXD Agency is Edition 1." },
  { id: "purpose", text: "Every feature must have a purpose." },
];

export const PLATFORM_PHASES: PlatformPhaseDefinition[] = [
  {
    id: "phase-6b",
    number: "6B",
    title: "Executive Dashboard",
    status: "completed",
    description: "Portfolio KPI aggregation, action center, and widget host for leadership briefing.",
    completedAt: "2025-12-01",
  },
  {
    id: "phase-8a",
    number: "8A",
    title: "Edition Framework",
    status: "completed",
    description: "Edition registry, module gating, branding, and navigation filtering for future SaaS evolution.",
    completedAt: "2026-02-01",
  },
  {
    id: "phase-10a",
    number: "10A",
    title: "Performance Reports",
    status: "completed",
    description: "Executive performance reporting extended through monthly-reports and lib/reporting.",
    completedAt: "2026-06-01",
  },
  {
    id: "phase-11a",
    number: "11A",
    title: "Architecture Assessment",
    status: "completed",
    description: "Full engineering architecture assessment of KXD OS before platform evolution.",
    completedAt: "2026-06-15",
  },
  {
    id: "phase-11b",
    number: "11B",
    title: "Platform Language Map",
    status: "completed",
    description: "Engineering naming and classification map for SaaS evolution — keep, abstract, rename guidance.",
    completedAt: "2026-06-20",
  },
  {
    id: "phase-11c",
    number: "11C",
    title: "Platform Boundary Inventory",
    status: "completed",
    description: "Subsystem-by-subsystem boundary inventory, dependency map, maturity assessment, and build priorities.",
    completedAt: "2026-06-25",
  },
  {
    id: "phase-11d",
    number: "11D",
    title: "Platform Progress Dashboard",
    status: "completed",
    description: "Internal engineering cockpit — platform completion, subsystem maturity, roadmap, and health metrics.",
    completedAt: "2026-07-06",
  },
  {
    id: "phase-12a2",
    number: "12A.2",
    title: "KXD Work Items Foundation",
    status: "completed",
    description: "Work Items facade, schema extensions, Activity Engine hooks, Client Command Work tab, portal request spawning.",
    completedAt: "2026-07-06",
  },
  {
    id: "phase-20e",
    number: "20E",
    title: "Executive Activity Engine",
    status: "completed",
    description:
      "Unified activity stream with publish/read services and Activity Center — foundation for Brief, Snapshot, and future Notification Center.",
    completedAt: "2026-07-11",
  },
  {
    id: "phase-20f",
    number: "20F",
    title: "Training & Enablement Workspace",
    status: "completed",
    description:
      "Internal learning hub with Learning Paths, lesson experience, multi-learner progress, and Work Engine practice interfaces.",
    completedAt: "2026-07-11",
  },
  {
    id: "phase-20g",
    number: "20G",
    title: "KXD Operations Experience",
    status: "completed",
    description:
      "Operational confidence learning — OS vs human responsibility, guided walkthroughs, Intelligence mentor hooks, Executive Ops Coordinator growth path.",
    completedAt: "2026-07-11",
  },
  {
    id: "phase-21a",
    number: "21A",
    title: "Executive Workspace",
    status: "completed",
    description:
      "Permanent shared operating environment — Executive Header, Activity drawer, Universal Search entry, Quick Create, Workspace Memory, and motion language across authenticated KXD OS surfaces.",
    completedAt: "2026-07-11",
  },
  {
    id: "phase-21b",
    number: "21B",
    title: "KXD Intelligence Layer",
    status: "completed",
    description:
      "Permanent operational reasoning layer — structured insights and recommendations over Brain, Pulse, Activity, and Memory. Not a chatbot. Workspaces consult one service before inventing local logic.",
    completedAt: "2026-07-11",
  },
  {
    id: "phase-21c",
    number: "21C",
    title: "Operations Intelligence Mentor",
    status: "completed",
    description:
      "First production mentor integration in Operations Experience — contextual guidance via lib/kxd-intelligence, intentional requests only, deterministic lesson-aware responses with escalation boundaries.",
    completedAt: "2026-07-11",
  },
  {
    id: "phase-22a",
    number: "22A",
    title: "Executive Today Workspace",
    status: "completed",
    description:
      "Permanent KXD OS home — composes Morning Brief, Work, Activity, and Intelligence into one calm editorial landing. Brief redirects into Today.",
    completedAt: "2026-07-11",
  },
  {
    id: "phase-22b",
    number: "22B",
    title: "Executive Experience Refinement",
    status: "completed",
    description:
      "Polish pass on Executive Today — priority hierarchy, activity noise reduction, glass header, Quick Capture surface, and motion using existing tokens.",
    completedAt: "2026-07-11",
  },
  {
    id: "phase-23a",
    number: "23A",
    title: "Executive Context Engine",
    status: "completed",
    description:
      "Shared awareness layer — getExecutiveContext composes Work, Activity, Brief, and Intelligence facts for every workspace. Today consumes Context; no new reasoning.",
    completedAt: "2026-07-11",
  },
  {
    id: "phase-23b",
    number: "23B",
    title: "Executive Signal Engine",
    status: "completed",
    description:
      "Filters, scores, groups, and prioritizes Activity Engine events for founder attention. Executive Today shows getExecutiveSignals() — max 6, no fabricated activity.",
    completedAt: "2026-07-11",
  },
  {
    id: "phase-24a",
    number: "24A",
    title: "Work Planning & Daily Execution",
    status: "completed",
    description:
      "URL-driven Work views, plannedForDate daily planning, quick actions, filters, and Recommended sort — ClickUp-class execution without Kanban.",
    completedAt: "2026-07-11",
  },
  {
    id: "phase-24b",
    number: "24B",
    title: "Operational Flow",
    status: "completed",
    description:
      "Quiet OS rebalancing after meaningful transitions — continuation, focus, signals, and path refresh without duplicate events or AI.",
    completedAt: "2026-07-11",
  },
  {
    id: "phase-24c",
    number: "24C",
    title: "Executive Work Composer v2",
    status: "completed",
    description:
      "Premium capture experience — Title, Description, Client, Due Date first; More details disclosure; reserved intelligence slot; keyboard-first.",
    completedAt: "2026-07-11",
  },
  {
    id: "phase-25a",
    number: "25A",
    title: "Executive Scheduling Architecture",
    status: "completed",
    description:
      "Architecture audit for Work↔Google Calendar scheduling — source of truth, hybrid domain model, Heather permission levels, sync/approval boundaries.",
    completedAt: "2026-07-11",
  },
  {
    id: "phase-25b",
    number: "25B",
    title: "Scheduling Domain Foundation",
    status: "completed",
    description:
      "Durable work-schedule-links, Work projections, policy/lifecycle/permissions, proposal APIs — no Google Calendar reads or writes.",
    completedAt: "2026-07-11",
  },
  {
    id: "phase-25c",
    number: "25C",
    title: "Google Calendar Read Foundation",
    status: "completed",
    description:
      "OAuth 2.0 calendar.readonly foundation — list calendars, timezone, free/busy, provider interfaces for Scheduling. No event writes.",
    completedAt: "2026-07-11",
  },
  {
    id: "phase-12",
    number: "12",
    title: "Timeline Unification",
    status: "planned",
    description: "Retire legacy client-timeline-events writes; enforce Activity Engine as sole timeline ingress.",
  },
  {
    id: "phase-13",
    number: "13",
    title: "Workspace Consolidation",
    status: "planned",
    description: "Make Client Command canonical; consolidate or redirect Executive Client Workspace.",
  },
  {
    id: "phase-14",
    number: "14",
    title: "Automation Module Connection",
    status: "planned",
    description: "Wire Creative, Requests, Deliverables, and Portal to automation publishers.",
  },
  {
    id: "phase-15",
    number: "15",
    title: "Intelligence Performance",
    status: "planned",
    description: "Incremental context loading, per-client cache, and materialized health scores.",
  },
  {
    id: "phase-16",
    number: "16",
    title: "Live Analytics Completion",
    status: "planned",
    description: "GA4 and Search Console feeds into reporting metrics and portal analytics modules.",
  },
  {
    id: "phase-17",
    number: "17",
    title: "Lead Funnel Unification",
    status: "planned",
    description: "Normalize research-leads, sales-leads, and website-audits into a shared pipeline model.",
  },
];

/** Subsystem registry — sourced from Phase 11C boundary inventory. */
export const PLATFORM_SUBSYSTEMS: PlatformSubsystemDefinition[] = [
  {
    id: "editions",
    name: "Editions",
    category: "Platform",
    owner: "platform-owner",
    maturity: "alpha",
    completionPercent: 48,
    status: "active",
    dependencies: [],
    lastCompletedPhase: "11C",
    currentPhase: "11D",
    description: "Edition registry and module gating for future SaaS.",
  },
  {
    id: "activity-engine",
    name: "Activity Engine",
    category: "Operations",
    owner: "shared-core",
    maturity: "beta",
    completionPercent: 92,
    status: "active",
    dependencies: ["Timeline", "Intelligence"],
    lastCompletedPhase: "20E",
    currentPhase: "20E",
    href: "/admin/operations/timeline",
    description:
      "Executive Activity Engine — unified event backbone for Work, reviews, and client systems.",
  },
  {
    id: "operational-flow",
    name: "Operational Flow",
    category: "Platform",
    owner: "shared-core",
    maturity: "beta",
    completionPercent: 82,
    status: "active",
    dependencies: [
      "Work Engine",
      "Activity Engine",
      "Executive Context Engine",
      "Executive Signal Engine",
    ],
    lastCompletedPhase: "25B",
    currentPhase: "25B",
    href: "/admin/operations/today",
    description:
      "Observes meaningful state transitions and quietly rebalances Context, Signals, Focus, and related surfaces — no automation, no AI, no UI.",
  },
  {
    id: "executive-scheduling",
    name: "Executive Scheduling",
    category: "Platform",
    owner: "shared-core",
    maturity: "alpha",
    completionPercent: 28,
    status: "active",
    dependencies: ["Work Engine", "Operational Flow", "Activity Engine"],
    lastCompletedPhase: "25C",
    currentPhase: "25C",
    description:
      "Work↔calendar scheduling — domain foundation (25B) + Google Calendar read/OAuth (25C). Writes deferred to 25E.",
  },
  {
    id: "executive-signals",
    name: "Executive Signal Engine",
    category: "Platform",
    owner: "shared-core",
    maturity: "beta",
    completionPercent: 88,
    status: "active",
    dependencies: ["Activity Engine", "Executive Context Engine"],
    lastCompletedPhase: "23B",
    currentPhase: "23B",
    href: "/admin/operations/today",
    description:
      "Quality gate between Activity and Context — suppress noise, score impact, group duplicates, surface only CEO-grade signals.",
  },
  {
    id: "executive-context",
    name: "Executive Context Engine",
    category: "Platform",
    owner: "shared-core",
    maturity: "beta",
    completionPercent: 86,
    status: "active",
    dependencies: [
      "Executive Workspace",
      "Work Engine",
      "Activity Engine",
      "Executive Signal Engine",
      "KXD Intelligence Layer",
    ],
    lastCompletedPhase: "23B",
    currentPhase: "23B",
    href: "/admin/operations/today",
    description:
      "Shared awareness composition — focus, waiting, continuation, momentum. Facts for Intelligence; not a dashboard.",
  },
  {
    id: "executive-workspace",
    name: "Executive Workspace",
    category: "Platform",
    owner: "platform-owner",
    maturity: "beta",
    completionPercent: 94,
    status: "active",
    dependencies: [
      "Activity Engine",
      "Command Search",
      "Work Engine",
      "Executive Context Engine",
      "Executive Signal Engine",
    ],
    lastCompletedPhase: "23B",
    currentPhase: "23B",
    href: "/admin/operations/today",
    description:
      "Permanent OS shell and Executive Today home — Context-backed orientation with Signal-quality Activity.",
  },
  {
    id: "kxd-intelligence",
    name: "KXD Intelligence Layer",
    category: "Intelligence",
    owner: "shared-core",
    maturity: "beta",
    completionPercent: 82,
    status: "active",
    dependencies: [
      "Business Brain",
      "Pulse",
      "Activity Engine",
      "Business Memory",
      "Executive Workspace",
      "Intelligence",
    ],
    lastCompletedPhase: "21C",
    currentPhase: "21C",
    href: "/admin/training",
    description:
      "Permanent reasoning facade plus Operations Experience mentor — structured guidance, escalation boundaries, and provider-ready interpretation without chatbot UI.",
  },
  {
    id: "training",
    name: "Operations Experience",
    category: "Operations",
    owner: "shared-core",
    maturity: "beta",
    completionPercent: 90,
    status: "active",
    dependencies: ["Work Engine", "KXD Intelligence Layer"],
    lastCompletedPhase: "21C",
    currentPhase: "21C",
    href: "/admin/training",
    description:
      "Operational confidence learning with live KXD Intelligence mentor for lesson-contextual guidance.",
  },
  {
    id: "timeline",
    name: "Timeline",
    category: "Operations",
    owner: "shared-core",
    maturity: "beta",
    completionPercent: 70,
    status: "consolidation",
    dependencies: ["Activity Engine"],
    lastCompletedPhase: "11C",
    currentPhase: "12",
    href: "/admin/operations/timeline",
    description: "Executive relationship history — portfolio and per-client views.",
  },
  {
    id: "communications",
    name: "Communications",
    category: "Client Ops",
    owner: "shared-core",
    maturity: "beta",
    completionPercent: 78,
    status: "stable",
    dependencies: ["Activity Engine", "Client Command"],
    lastCompletedPhase: "11C",
    currentPhase: "—",
    href: "/admin/operations/client-command",
  },
  {
    id: "client-actions",
    name: "Client Actions",
    category: "Client Ops",
    owner: "shared-core",
    maturity: "beta",
    completionPercent: 76,
    status: "stable",
    dependencies: ["Activity Engine", "Intelligence"],
    lastCompletedPhase: "11C",
    currentPhase: "—",
    href: "/admin/operations/client-command",
  },
  {
    id: "client-command",
    name: "Client Command",
    category: "Client Ops",
    owner: "shared-core",
    maturity: "production",
    completionPercent: 95,
    status: "stable",
    dependencies: ["Intelligence", "Financial Command", "Timeline"],
    lastCompletedPhase: "11C",
    currentPhase: "13",
    href: "/admin/operations/client-command",
    description: "Primary per-client operational HQ.",
  },
  {
    id: "client-workspace",
    name: "Client Workspace",
    category: "Client Ops",
    owner: "shared-core",
    maturity: "alpha",
    completionPercent: 42,
    status: "consolidation",
    dependencies: ["Client Command"],
    lastCompletedPhase: "11C",
    currentPhase: "13",
    href: "/admin/operations/clients",
    description: "Parallel executive workspace — consolidation planned.",
  },
  {
    id: "executive-dashboard",
    name: "Executive Dashboard",
    category: "Leadership",
    owner: "shared-core",
    maturity: "production",
    completionPercent: 94,
    status: "stable",
    dependencies: ["Intelligence", "Financial Command", "Sales"],
    lastCompletedPhase: "10A",
    currentPhase: "—",
    href: "/admin/operations/executive",
  },
  {
    id: "reporting",
    name: "Reporting",
    category: "Intelligence",
    owner: "shared-core",
    maturity: "beta",
    completionPercent: 80,
    status: "active",
    dependencies: ["Intelligence", "Live Integrations"],
    lastCompletedPhase: "10A",
    currentPhase: "16",
    href: "/admin/operations/reports",
  },
  {
    id: "financial-command",
    name: "Financial Command",
    category: "Finance",
    owner: "shared-core",
    maturity: "beta",
    completionPercent: 75,
    status: "stable",
    dependencies: ["Sales", "Contracts"],
    lastCompletedPhase: "11C",
    currentPhase: "—",
    href: "/admin/operations/accounts",
  },
  {
    id: "proposal-system",
    name: "Proposal System",
    category: "Sales",
    owner: "shared-core",
    maturity: "production",
    completionPercent: 90,
    status: "stable",
    dependencies: ["Sales", "Contracts", "Client Launch"],
    lastCompletedPhase: "11C",
    currentPhase: "17",
    href: "/admin/sales/proposals",
  },
  {
    id: "sales",
    name: "Sales",
    category: "Sales",
    owner: "shared-core",
    maturity: "production",
    completionPercent: 93,
    status: "stable",
    dependencies: ["Proposal System"],
    lastCompletedPhase: "11C",
    currentPhase: "17",
    href: "/admin/sales",
  },
  {
    id: "contracts",
    name: "Contracts",
    category: "Sales",
    owner: "shared-core",
    maturity: "beta",
    completionPercent: 74,
    status: "stable",
    dependencies: ["Sales", "Financial Command"],
    lastCompletedPhase: "11C",
    currentPhase: "—",
    href: "/admin/operations/client-command",
  },
  {
    id: "intelligence",
    name: "Intelligence",
    category: "Intelligence",
    owner: "shared-core",
    maturity: "production",
    completionPercent: 96,
    status: "stable",
    dependencies: [],
    lastCompletedPhase: "11C",
    currentPhase: "15",
    href: "/admin/operations/founder-intelligence",
    description: "Deterministic portfolio context and recommendations.",
  },
  {
    id: "brain",
    name: "Brain",
    category: "Intelligence",
    owner: "shared-core",
    maturity: "beta",
    completionPercent: 78,
    status: "active",
    dependencies: ["Intelligence", "Automation", "Live Integrations"],
    lastCompletedPhase: "11C",
    currentPhase: "15",
    href: "/admin/operations/brain",
  },
  {
    id: "search",
    name: "Search",
    category: "Platform",
    owner: "shared-core",
    maturity: "production",
    completionPercent: 94,
    status: "stable",
    dependencies: ["Intelligence", "Editions"],
    lastCompletedPhase: "11C",
    currentPhase: "—",
  },
  {
    id: "notifications",
    name: "Notifications",
    category: "Platform",
    owner: "shared-core",
    maturity: "beta",
    completionPercent: 68,
    status: "stable",
    dependencies: ["Automation"],
    lastCompletedPhase: "11C",
    currentPhase: "14",
  },
  {
    id: "automation",
    name: "Automation",
    category: "Platform",
    owner: "platform-owner",
    maturity: "beta",
    completionPercent: 72,
    status: "active",
    dependencies: ["Timeline", "Notifications"],
    lastCompletedPhase: "11C",
    currentPhase: "14",
    href: "/admin/operations/automation",
  },
  {
    id: "portal",
    name: "Portal",
    category: "Client Experience",
    owner: "shared-core",
    maturity: "beta",
    completionPercent: 76,
    status: "active",
    dependencies: ["Reporting", "Financial Command", "Editions"],
    lastCompletedPhase: "11C",
    currentPhase: "16",
    href: "/portal",
    description: "Client HQ — core modules live; analytics and advisor scaffolded.",
  },
  {
    id: "client-onboarding",
    name: "Client Onboarding",
    category: "Client Ops",
    owner: "shared-core",
    maturity: "production",
    completionPercent: 91,
    status: "stable",
    dependencies: ["Automation", "Portal"],
    lastCompletedPhase: "11C",
    currentPhase: "—",
    href: "/admin/operations/onboarding",
  },
  {
    id: "client-success",
    name: "Client Success",
    category: "Client Ops",
    owner: "shared-core",
    maturity: "alpha",
    completionPercent: 50,
    status: "planned",
    dependencies: ["Intelligence", "Automation"],
    lastCompletedPhase: "11C",
    currentPhase: "—",
    href: "/admin/operations/client-success",
  },
  {
    id: "infrastructure",
    name: "Infrastructure",
    category: "Operations",
    owner: "shared-core",
    maturity: "beta",
    completionPercent: 77,
    status: "stable",
    dependencies: ["Live Integrations"],
    lastCompletedPhase: "11C",
    currentPhase: "—",
    href: "/admin/operations/infrastructure",
  },
  {
    id: "website-auditor",
    name: "Website Auditor",
    category: "Growth",
    owner: "agency-edition",
    maturity: "production",
    completionPercent: 92,
    status: "stable",
    dependencies: ["Automation", "Sales"],
    lastCompletedPhase: "11C",
    currentPhase: "17",
    href: "/admin/operations/audits",
  },
  {
    id: "creative",
    name: "Creative Engine",
    category: "Studio",
    owner: "agency-edition",
    maturity: "beta",
    completionPercent: 74,
    status: "active",
    dependencies: ["Integrations"],
    lastCompletedPhase: "11C",
    currentPhase: "14",
    href: "/admin/operations/creative",
  },
  {
    id: "junior-creators",
    name: "Junior Creators",
    category: "Studio",
    owner: "agency-edition",
    maturity: "beta",
    completionPercent: 72,
    status: "stable",
    dependencies: ["Research"],
    lastCompletedPhase: "11C",
    currentPhase: "—",
    href: "/admin/operations/junior-creators",
  },
  {
    id: "research",
    name: "Research Leads",
    category: "Growth",
    owner: "agency-edition",
    maturity: "alpha",
    completionPercent: 46,
    status: "consolidation",
    dependencies: ["Sales"],
    lastCompletedPhase: "11C",
    currentPhase: "17",
    href: "/admin/operations/research",
  },
  {
    id: "playbooks",
    name: "Playbooks",
    category: "Operations",
    owner: "shared-core",
    maturity: "beta",
    completionPercent: 75,
    status: "stable",
    dependencies: ["Automation", "Timeline"],
    lastCompletedPhase: "11C",
    currentPhase: "—",
    href: "/admin/operations/playbooks",
  },
  {
    id: "genesis",
    name: "Genesis",
    category: "Client Ops",
    owner: "shared-core",
    maturity: "beta",
    completionPercent: 78,
    status: "stable",
    dependencies: ["Client Onboarding", "Playbooks"],
    lastCompletedPhase: "11C",
    currentPhase: "—",
    href: "/admin/operations/genesis",
  },
  {
    id: "launch-qa",
    name: "Launch QA",
    category: "Operations",
    owner: "shared-core",
    maturity: "beta",
    completionPercent: 76,
    status: "stable",
    dependencies: ["Live Integrations", "Playbooks"],
    lastCompletedPhase: "11C",
    currentPhase: "—",
    href: "/admin/operations/launch-qa",
  },
  {
    id: "integrations",
    name: "Integrations",
    category: "Platform",
    owner: "platform-owner",
    maturity: "beta",
    completionPercent: 73,
    status: "active",
    dependencies: [],
    lastCompletedPhase: "11C",
    currentPhase: "16",
    href: "/admin/operations/integrations",
  },
  {
    id: "live-integrations",
    name: "Live Integrations",
    category: "Platform",
    owner: "platform-owner",
    maturity: "beta",
    completionPercent: 68,
    status: "active",
    dependencies: ["Integrations", "Brain"],
    lastCompletedPhase: "11C",
    currentPhase: "16",
    href: "/admin/operations/integrations",
  },
];
