/**
 * Primal Motorsports — Executive Memory (Phase 32A.1 integrity pass).
 *
 * Evidence-backed for briefing. EP presentation bridges keep prior exact labels
 * so Executive Performance remains visually unchanged.
 *
 * Classifications follow repository + seed + validation evidence — not case-study prose.
 */

import type { ExecutiveMemoryItem } from "../types";

export const PRIMAL_MOTORSPORTS_MEMORY: ExecutiveMemoryItem[] = [
  {
    id: "identity",
    kind: "identity",
    status: "active",
    label: "Primal Motorsports",
    statement:
      "Primal Motorsports is a Radical Cup North America racing team and automotive brand whose digital partnership with Kreate by Design is actively underway.",
    occurredAt: null,
    evidenceLabels: ["client:primal-motorsports", "seed:clients", "phase-18c"],
    evidenceStrength: "verified",
    briefingSection: "hidden",
  },
  {
    id: "relationship-active",
    kind: "relationship",
    status: "active",
    label: "Active partnership",
    statement:
      "An active flagship partnership oriented toward launching the rebuilt website cleanly, refining advertising carefully, and giving leadership a calm operating view.",
    occurredAt: null,
    evidenceLabels: ["relationship:active", "seed:executive-profiles", "retainer:configured"],
    evidenceStrength: "verified",
    briefingSection: "hidden",
  },

  /* ── Partnership progress strip (exact EP labels — do not alter) ─ */
  {
    id: "website-rebuild",
    kind: "website",
    status: "completed",
    label: "Your website, rebuilt",
    statement: "We've rebuilt the flagship site and refined it toward launch readiness.",
    briefingStatement:
      "The flagship website has been rebuilt and refined on staging. Production launch follows final revisions from leadership.",
    occurredAt: null,
    evidenceLabels: [
      "infra:stagingUrl",
      "seed:executive-profiles:awaiting-revisions",
    ],
    evidenceStrength: "verified",
    priority: true,
    briefingSection: "built",
    presentation: { partnershipItemId: "website-rebuild" },
  },
  {
    id: "landing-pages",
    kind: "website",
    status: "completed",
    label: "Landing experiences shaped with care",
    statement:
      "Pages designed to meet people arriving from advertising — clear, composed, and on-brand.",
    occurredAt: null,
    evidenceLabels: ["editorial:ep-bridge"],
    evidenceStrength: "insufficient",
    priority: true,
    /* Keep EP strip; exclude from briefing until independently verified. */
    briefingSection: "hidden",
    presentation: { partnershipItemId: "landing-pages" },
  },
  {
    id: "google-ads",
    kind: "advertising",
    status: "active",
    label: "Advertising refined with care",
    statement: "Google Ads work that protects investment and attracts qualified interest.",
    briefingStatement:
      "Google Ads has been actively managed in the partnership. Prepared performance reports summarize results; live Ads ReportingFacts are not yet connected in KXD OS.",
    occurredAt: null,
    evidenceLabels: [
      "seed:executive-profiles:google-ads",
      "monthly-reports:google_ads",
      "provider:ads:not-implemented",
    ],
    evidenceStrength: "supported",
    priority: true,
    briefingSection: "marketing",
    presentation: { partnershipItemId: "google-ads" },
  },
  {
    id: "seo",
    kind: "seo",
    status: "active",
    label: "Search presence established",
    statement:
      "Foundational search work is in place so people can find you more clearly over time.",
    briefingStatement:
      "Search Console is connected. Live search metrics appear when ReportingFacts exist for the selected period.",
    occurredAt: null,
    evidenceLabels: [
      "capability:seo",
      "provider:google-search-console",
      "configure:primal-reporting",
    ],
    evidenceStrength: "verified",
    priority: true,
    briefingSection: "marketing",
    presentation: { partnershipItemId: "seo" },
  },
  {
    id: "website-review",
    kind: "portal",
    status: "active",
    label: "A private place to refine the site together",
    statement: "Website Review keeps revision notes organized in one private place.",
    occurredAt: null,
    evidenceLabels: ["system:website-review", "phase-18c", "enabledModules:website-review"],
    evidenceStrength: "verified",
    priority: true,
    briefingSection: "systems",
    presentation: { partnershipItemId: "website-review" },
  },
  {
    id: "reporting",
    kind: "reporting",
    status: "active",
    label: "Executive clarity, prepared",
    statement:
      "This workspace is structured so leadership can see what matters when signals are ready.",
    briefingStatement:
      "Executive Performance is enabled for leadership — calm reporting when live facts are present, never fabricated numbers.",
    occurredAt: null,
    evidenceLabels: ["system:executive-performance", "enabledModules:executive-performance"],
    evidenceStrength: "verified",
    priority: true,
    briefingSection: "systems",
    presentation: { partnershipItemId: "reporting" },
  },
  {
    id: "portal",
    kind: "portal",
    status: "active",
    label: "Your private partnership workspace",
    statement:
      "A quiet operating environment built for leadership — not a generic client portal.",
    occurredAt: null,
    evidenceLabels: ["system:ces-portal", "phase-18c", "phase-18f"],
    evidenceStrength: "verified",
    priority: false,
    briefingSection: "systems",
    presentation: { partnershipItemId: "portal" },
  },

  /* ── Milestone strip (exact EP labels + order) ─────────────────── */
  {
    id: "milestone-website-rebuilt",
    kind: "milestone",
    status: "completed",
    label: "Your website, rebuilt for the brand",
    statement: "We rebuilt the flagship website for the brand.",
    briefingStatement:
      "The rebuilt website exists on staging and continues to be refined for launch.",
    occurredAt: null,
    evidenceLabels: ["infra:stagingUrl"],
    evidenceStrength: "verified",
    briefingSection: "hidden",
    presentation: {
      milestoneId: "website-rebuilt",
      milestoneLabel: "Your website, rebuilt for the brand",
    },
  },
  {
    id: "milestone-google-ads-launched",
    kind: "milestone",
    status: "completed",
    label: "Advertising launched and refined together",
    statement: "We launched Google Ads and continue refining them together.",
    occurredAt: null,
    evidenceLabels: ["seed:executive-profiles:google-ads", "monthly-reports:google_ads"],
    evidenceStrength: "supported",
    briefingSection: "hidden",
    presentation: {
      milestoneId: "google-ads-launched",
      milestoneLabel: "Advertising launched and refined together",
    },
  },
  {
    id: "milestone-conversion-tracking",
    kind: "milestone",
    status: "completed",
    label: "Lead tracking verified and working",
    statement: "Lead tracking was verified and is working.",
    occurredAt: null,
    evidenceLabels: ["prepared-report:conversion-language", "editorial:ep-milestone"],
    evidenceStrength: "editorial",
    briefingSection: "hidden",
    presentation: {
      milestoneId: "conversion-tracking",
      milestoneLabel: "Lead tracking verified and working",
    },
  },
  {
    id: "milestone-review-workflow",
    kind: "milestone",
    status: "completed",
    label: "A private review rhythm introduced",
    statement: "We introduced Website Review as a private review rhythm.",
    occurredAt: null,
    evidenceLabels: ["system:website-review", "phase-18c"],
    evidenceStrength: "verified",
    briefingSection: "hidden",
    presentation: {
      milestoneId: "review-workflow",
      milestoneLabel: "A private review rhythm introduced",
    },
  },
  {
    id: "milestone-operating-portal",
    kind: "milestone",
    status: "completed",
    label: "Your partnership workspace opened",
    statement: "We opened the private partnership workspace for leadership.",
    occurredAt: null,
    evidenceLabels: ["system:ces-portal", "phase-18c"],
    evidenceStrength: "verified",
    briefingSection: "hidden",
    presentation: {
      milestoneId: "operating-portal",
      milestoneLabel: "Your partnership workspace opened",
    },
  },
  {
    id: "milestone-executive-collaboration",
    kind: "milestone",
    status: "completed",
    label: "Closer collaboration with leadership",
    statement: "Closer collaboration with leadership is now part of the operating rhythm.",
    occurredAt: null,
    evidenceLabels: ["system:executive-performance"],
    evidenceStrength: "verified",
    briefingSection: "hidden",
    presentation: {
      milestoneId: "executive-collaboration",
      milestoneLabel: "Closer collaboration with leadership",
    },
  },
  {
    id: "milestone-launch-readiness",
    kind: "milestone",
    status: "in-progress",
    label: "Launch readiness strengthened",
    statement: "Launch readiness continues to be strengthened together.",
    occurredAt: null,
    evidenceLabels: ["seed:executive-profiles:awaiting-revisions"],
    evidenceStrength: "verified",
    briefingSection: "current",
    presentation: {
      milestoneId: "launch-readiness",
      milestoneLabel: "Launch readiness strengthened",
    },
  },

  /* ── Editorial story beats (exact EP journey labels) ──────────── */
  {
    id: "story-strategy",
    kind: "milestone",
    status: "completed",
    label: "Website direction set together",
    statement: "Website strategy and direction were set together at the start of the rebuild.",
    occurredAt: null,
    evidenceLabels: ["story:strategy", "project:primal-motorsports"],
    evidenceStrength: "supported",
    briefingSection: "hidden",
    presentation: { storyBeatId: "story-strategy" },
  },
  {
    id: "story-ads",
    kind: "milestone",
    status: "completed",
    label: "Advertising launched with care",
    statement: "Advertising launched and continues under active refinement.",
    occurredAt: null,
    evidenceLabels: ["story:ads", "seed:executive-profiles:google-ads"],
    evidenceStrength: "supported",
    briefingSection: "hidden",
    presentation: { storyBeatId: "story-ads" },
  },
  {
    id: "story-workspace",
    kind: "milestone",
    status: "completed",
    label: "Your private workspace introduced",
    statement: "A private partnership workspace was introduced for leadership.",
    occurredAt: null,
    evidenceLabels: ["story:workspace", "phase-18c"],
    evidenceStrength: "verified",
    briefingSection: "hidden",
    presentation: { storyBeatId: "story-workspace" },
  },
  {
    id: "story-review",
    kind: "milestone",
    status: "completed",
    label: "A shared review rhythm established",
    statement: "A shared Website Review rhythm was established for confident refinement.",
    occurredAt: null,
    evidenceLabels: ["story:review", "system:website-review"],
    evidenceStrength: "verified",
    briefingSection: "hidden",
    presentation: { storyBeatId: "story-review" },
  },
  {
    id: "story-prep",
    kind: "launch",
    status: "in-progress",
    label: "Preparing for launch together",
    statement: "Launch preparation remains underway together.",
    briefingStatement:
      "KXD continues launch preparation on the rebuilt site while final leadership revisions complete.",
    occurredAt: null,
    evidenceLabels: ["story:prep", "seed:executive-profiles:awaiting-revisions"],
    evidenceStrength: "verified",
    briefingSection: "current",
    presentation: { storyBeatId: "story-prep" },
  },
  {
    id: "story-launch",
    kind: "launch",
    status: "planned",
    label: "Launch",
    statement: "Website launch is the next major milestone ahead.",
    briefingStatement:
      "Website launch follows final revisions — the clear next partnership milestone.",
    occurredAt: null,
    evidenceLabels: ["story:launch"],
    evidenceStrength: "verified",
    briefingSection: "next",
    presentation: { storyBeatId: "story-launch" },
  },

  /* ── Awaiting client (calm, not shaming) ──────────────────────── */
  {
    id: "awaiting-website-revisions",
    kind: "priority",
    status: "in-progress",
    label: "Website revisions with leadership",
    statement:
      "Final website revisions are with Primal leadership. When those notes are complete, launch can move forward cleanly.",
    occurredAt: null,
    evidenceLabels: [
      "seed:executive-profiles:awaiting-Adam-Tyler-revisions",
      "placeholders:awaiting-client-revisions",
    ],
    evidenceStrength: "verified",
    awaitingOwner: "client",
    briefingSection: "awaiting",
  },

  /* ── Connected reporting systems ──────────────────────────────── */
  {
    id: "search-console-connected",
    kind: "reporting",
    status: "completed",
    label: "Search Console connected",
    statement:
      "We connected Search Console and surface live clicks, impressions, CTR, and position when ReportingFacts exist for the period.",
    occurredAt: null,
    evidenceLabels: ["provider:google-search-console", "facts:search"],
    evidenceStrength: "verified",
    briefingSection: "results",
  },
  {
    id: "executive-performance-introduced",
    kind: "reporting",
    status: "active",
    label: "Executive Performance introduced",
    statement: "We introduced Executive Performance as the calm leadership view of the partnership.",
    occurredAt: null,
    evidenceLabels: ["system:executive-performance"],
    evidenceStrength: "verified",
    briefingSection: "systems",
  },
  {
    id: "ga4-prepared",
    kind: "reporting",
    status: "planned",
    label: "Website analytics (GA4)",
    statement:
      "Website analytics are prepared in KXD OS. They will appear automatically once GA4 access is verified and the website-analytics entitlement is enabled.",
    occurredAt: null,
    evidenceLabels: [
      "ga4:property:530873364",
      "entitlement:website-analytics:held",
      "provider:ga4:pipeline-ready",
    ],
    evidenceStrength: "verified",
    briefingSection: "next",
  },

  /* ── Primal OS — future opportunity only (not included / not purchased) */
  {
    id: "platform-primal-os",
    kind: "platform",
    status: "planned",
    label: "Primal OS",
    statement:
      "As Primal continues to grow, there are opportunities to expand beyond today's website and workspace. Those conversations stay separate from the current engagement.",
    occurredAt: null,
    evidenceLabels: [
      "case-study:primal-os-scoped",
      "seed:executive-profiles:foundation-development",
      "platforms:motorsports-os",
      "repo:no-primal-os-implementation",
    ],
    evidenceStrength: "supported",
    briefingSection: "platform",
    platformOpportunity: {
      title: "Future Opportunities",
      positioning:
        "As Primal continues to grow, there are opportunities to expand beyond today's website and workspace.",
      capabilities: [
        "Driver management",
        "Team operations",
        "Internal reporting",
        "Driver portal experiences",
      ],
      pricing: {
        mode: "prepared-separately",
        models: [
          { id: "implementation", label: "One-time implementation", amountLabel: null },
          { id: "monthly", label: "Monthly platform / support", amountLabel: null },
          {
            id: "bundle",
            label: "Implementation + monthly support",
            amountLabel: null,
          },
          { id: "phased", label: "Phased rollout", amountLabel: null },
          { id: "custom", label: "Custom scope", amountLabel: null },
        ],
        note: "Pricing prepared separately based on selected capabilities.",
      },
    },
  },

  /* ── Growth opportunities (exact EP evolution copy) ───────────── */
  {
    id: "opportunity-lead-mgmt",
    kind: "opportunity",
    status: "planned",
    label: "Lead Management",
    statement:
      "A clearer path from inquiry to conversation — so promising interest is never left waiting.",
    occurredAt: null,
    evidenceLabels: ["evolution:lead-management"],
    evidenceStrength: "editorial",
    priority: true,
    briefingSection: "next",
    presentation: { evolutionId: "lead-management" },
  },
  {
    id: "opportunity-exec-reporting",
    kind: "opportunity",
    status: "planned",
    label: "Executive Reporting",
    statement:
      "A calm, recurring view of what is moving the business — prepared for leadership, not buried in tools.",
    occurredAt: null,
    evidenceLabels: ["evolution:executive-reporting"],
    evidenceStrength: "editorial",
    priority: true,
    briefingSection: "next",
    presentation: { evolutionId: "executive-reporting" },
  },
  {
    id: "opportunity-customer-journey",
    kind: "opportunity",
    status: "planned",
    label: "Customer Journey",
    statement:
      "One continuous picture from first interest to long-term relationship — marketing, site, and follow-through together.",
    occurredAt: null,
    evidenceLabels: ["evolution:customer-journey"],
    evidenceStrength: "editorial",
    briefingSection: "next",
    presentation: { evolutionId: "customer-journey" },
  },
  {
    id: "opportunity-expansion",
    kind: "opportunity",
    status: "planned",
    label: "Expansion",
    statement:
      "Room to grow into new programs when the partnership has the capacity — paced thoughtfully, never rushed.",
    occurredAt: null,
    evidenceLabels: ["evolution:expansion"],
    evidenceStrength: "editorial",
    briefingSection: "next",
    presentation: { evolutionId: "expansion" },
  },
];
