/**
 * Primal Motorsports — Executive Memory (post-launch baseline · September 11, 2026).
 *
 * Evidence-backed for briefing and Executive Performance.
 * Classifications follow verified launch + post-launch work — not marketing prose.
 */

import type { ExecutiveMemoryItem } from "../types";

export const PRIMAL_MOTORSPORTS_MEMORY: ExecutiveMemoryItem[] = [
  {
    id: "identity",
    kind: "identity",
    status: "active",
    label: "Primal Motorsports",
    statement:
      "Primal Motorsports is a Radical Cup North America racing team and automotive brand in an active digital partnership with Kreate by Design.",
    occurredAt: null,
    evidenceLabels: ["client:primal-motorsports", "seed:clients", "phase-18c"],
    evidenceStrength: "verified",
    briefingSection: "hidden",
  },
  {
    id: "relationship-active",
    kind: "relationship",
    status: "active",
    label: "Active partnership",
    statement:
      "An active flagship partnership focused on a live production website, protected search equity, careful advertising, and clear leadership reporting.",
    occurredAt: null,
    evidenceLabels: ["relationship:active", "seed:executive-profiles", "retainer:configured"],
    evidenceStrength: "verified",
    briefingSection: "hidden",
  },
  {
    id: "operating-phase",
    kind: "priority",
    status: "active",
    label: "Growth & Optimization",
    statement:
      "Production is live and verified. The current phase is growth and optimization — qualified traffic, search visibility, and advertising efficiency.",
    briefingStatement:
      "Current phase: Growth & Optimization. Priority: increase qualified traffic and lead performance.",
    occurredAt: "2026-09-11",
    evidenceLabels: ["launch:2026-09-09", "baseline:2026-09-11", "leadership-report:september-2026"],
    evidenceStrength: "verified",
    priority: true,
    briefingSection: "current",
  },

  /* ── Partnership progress strip ───────────────────────────────── */
  {
    id: "website-rebuild",
    kind: "website",
    status: "completed",
    label: "Production website live",
    statement: "The new Primal Motorsports website is live in production.",
    briefingStatement:
      "The new Primal Motorsports website launched September 9, 2026. Production verification is complete.",
    occurredAt: "2026-09-09",
    evidenceLabels: ["launch:2026-09-09", "infra:production", "leadership-report:september-2026"],
    evidenceStrength: "verified",
    priority: true,
    briefingSection: "built",
    presentation: { partnershipItemId: "website-rebuild" },
  },
  {
    id: "production-verified",
    kind: "website",
    status: "completed",
    label: "Production verified",
    statement: "Post-launch technical verification across search, leads, performance, and commercial routes is complete.",
    briefingStatement:
      "Following launch, KXD completed a full technical verification pass. Final post-launch production status: verified.",
    occurredAt: "2026-09-11",
    evidenceLabels: ["verification:2026-09-11", "leadership-report:post-launch"],
    evidenceStrength: "verified",
    priority: true,
    briefingSection: "built",
    presentation: { partnershipItemId: "production-verified" },
  },
  {
    id: "landing-pages",
    kind: "website",
    status: "completed",
    label: "Racing School and program paths live",
    statement:
      "Racing Schools, Driving Programs, Radical inventory, Service, Parts, and Contact paths are live on the production site.",
    occurredAt: "2026-09-09",
    evidenceLabels: ["platform:racing-schools", "platform:radical", "platform:commercial-paths"],
    evidenceStrength: "verified",
    priority: true,
    briefingSection: "built",
    presentation: { partnershipItemId: "landing-pages" },
  },
  {
    id: "google-ads",
    kind: "advertising",
    status: "active",
    label: "Google Ads audited and converting",
    statement: "Google Ads is active, audited, and recording tracked primary conversions.",
    briefingStatement:
      "Google Ads was audited for August 12 – September 10, 2026. Primary conversions are tracking. Live Ads panel sync in this workspace remains separate from the verified Leadership Report figures.",
    occurredAt: "2026-09-11",
    evidenceLabels: [
      "ads-audit:2026-08-12-to-2026-09-10",
      "leadership-report:ads",
      "provider:google-ads:pipeline-ready",
      "entitlement:google-ads:held",
    ],
    evidenceStrength: "verified",
    priority: true,
    briefingSection: "marketing",
    presentation: { partnershipItemId: "google-ads" },
  },
  {
    id: "seo",
    kind: "seo",
    status: "active",
    label: "Search foundation active",
    statement:
      "Technical SEO, Search Console measurement, and legacy URL protection are in place on the live site.",
    briefingStatement:
      "Search foundation is active: metadata, sitemap, robots, structured data, internal links, and legacy redirects. Search Console is connected for the partnership. Live panel numbers appear when ReportingFacts exist for the selected period.",
    occurredAt: "2026-09-11",
    evidenceLabels: [
      "capability:seo",
      "provider:google-search-console",
      "seo:redirects",
      "seo:schema",
      "seo:sitemap",
      "configure:primal-reporting",
    ],
    evidenceStrength: "verified",
    priority: true,
    briefingSection: "marketing",
    presentation: { partnershipItemId: "seo" },
  },
  {
    id: "website-review",
    kind: "portal",
    status: "active",
    label: "Private place for future site updates",
    statement:
      "Website Review remains available for future notes — it is no longer the launch gate.",
    occurredAt: null,
    evidenceLabels: ["system:website-review", "phase-18c", "enabledModules:website-review"],
    evidenceStrength: "verified",
    priority: false,
    briefingSection: "systems",
    presentation: { partnershipItemId: "website-review" },
  },
  {
    id: "reporting",
    kind: "reporting",
    status: "active",
    label: "Leadership reporting ready",
    statement:
      "Executive Performance and the Leadership Report give leadership a clear view of status, performance, and next priorities.",
    briefingStatement:
      "September 11, 2026 is the documented post-launch baseline. The Leadership Report holds verified organic, Ads, and post-launch verification detail.",
    occurredAt: "2026-09-11",
    evidenceLabels: [
      "system:executive-performance",
      "leadership-report:september-2026",
      "enabledModules:executive-performance",
    ],
    evidenceStrength: "verified",
    priority: true,
    briefingSection: "systems",
    presentation: { partnershipItemId: "reporting" },
  },
  {
    id: "portal",
    kind: "portal",
    status: "active",
    label: "Your private partnership workspace",
    statement:
      "A quiet operating environment built for leadership — not a generic client portal.",
    occurredAt: null,
    evidenceLabels: ["system:ces-portal", "phase-18c", "phase-18f"],
    evidenceStrength: "verified",
    priority: false,
    briefingSection: "systems",
    presentation: { partnershipItemId: "portal" },
  },

  /* ── Milestone strip ──────────────────────────────────────────── */
  {
    id: "milestone-website-rebuilt",
    kind: "milestone",
    status: "completed",
    label: "Website rebuilt for the brand",
    statement: "The flagship website was rebuilt for Primal Motorsports.",
    briefingStatement: "The rebuilt website is live in production.",
    occurredAt: "2026-09-09",
    evidenceLabels: ["launch:2026-09-09"],
    evidenceStrength: "verified",
    briefingSection: "hidden",
    presentation: {
      milestoneId: "website-rebuilt",
      milestoneLabel: "Website rebuilt for the brand",
    },
  },
  {
    id: "milestone-website-launched",
    kind: "milestone",
    status: "completed",
    label: "Website launched",
    statement: "The new Primal Motorsports platform launched September 9, 2026.",
    occurredAt: "2026-09-09",
    evidenceLabels: ["launch:2026-09-09"],
    evidenceStrength: "verified",
    briefingSection: "built",
    presentation: {
      milestoneId: "website-launched",
      milestoneLabel: "Website launched · September 9, 2026",
    },
  },
  {
    id: "milestone-production-verified",
    kind: "milestone",
    status: "completed",
    label: "Post-launch verification complete",
    statement: "Production verification completed September 11, 2026.",
    occurredAt: "2026-09-11",
    evidenceLabels: ["verification:2026-09-11"],
    evidenceStrength: "verified",
    briefingSection: "built",
    presentation: {
      milestoneId: "production-verified",
      milestoneLabel: "Post-launch verification complete · September 11, 2026",
    },
  },
  {
    id: "milestone-google-ads-launched",
    kind: "milestone",
    status: "completed",
    label: "Advertising audited and refining",
    statement: "Google Ads launched earlier and continues under active refinement after the audit.",
    occurredAt: "2026-09-11",
    evidenceLabels: ["ads-audit:2026-08-12-to-2026-09-10"],
    evidenceStrength: "verified",
    briefingSection: "hidden",
    presentation: {
      milestoneId: "google-ads-launched",
      milestoneLabel: "Advertising audited and refining",
    },
  },
  {
    id: "milestone-conversion-tracking",
    kind: "milestone",
    status: "completed",
    label: "Lead and conversion tracking verified",
    statement: "Website lead tracking and Ads primary conversion tracking are verified as operating.",
    occurredAt: "2026-09-11",
    evidenceLabels: ["ga4:generate_lead", "ads:primary-conversions", "leadership-report:measurement"],
    evidenceStrength: "verified",
    briefingSection: "hidden",
    presentation: {
      milestoneId: "conversion-tracking",
      milestoneLabel: "Lead and conversion tracking verified",
    },
  },
  {
    id: "milestone-review-workflow",
    kind: "milestone",
    status: "completed",
    label: "Private review rhythm introduced",
    statement: "Website Review remains available for future updates.",
    occurredAt: null,
    evidenceLabels: ["system:website-review", "phase-18c"],
    evidenceStrength: "verified",
    briefingSection: "hidden",
    presentation: {
      milestoneId: "review-workflow",
      milestoneLabel: "Private review rhythm introduced",
    },
  },
  {
    id: "milestone-operating-portal",
    kind: "milestone",
    status: "completed",
    label: "Partnership workspace opened",
    statement: "The private partnership workspace is open for leadership.",
    occurredAt: null,
    evidenceLabels: ["system:ces-portal", "phase-18c"],
    evidenceStrength: "verified",
    briefingSection: "hidden",
    presentation: {
      milestoneId: "operating-portal",
      milestoneLabel: "Partnership workspace opened",
    },
  },
  {
    id: "milestone-executive-collaboration",
    kind: "milestone",
    status: "completed",
    label: "Leadership reporting in place",
    statement: "Executive Performance and the Leadership Report are available to leadership.",
    occurredAt: "2026-09-11",
    evidenceLabels: ["system:executive-performance", "leadership-report:september-2026"],
    evidenceStrength: "verified",
    briefingSection: "hidden",
    presentation: {
      milestoneId: "executive-collaboration",
      milestoneLabel: "Leadership reporting in place",
    },
  },
  {
    id: "milestone-growth-phase",
    kind: "milestone",
    status: "in-progress",
    label: "Growth and optimization underway",
    statement: "The partnership has moved from launch into measurable growth and optimization.",
    occurredAt: "2026-09-11",
    evidenceLabels: ["baseline:2026-09-11", "plan:30-60-90"],
    evidenceStrength: "verified",
    briefingSection: "current",
    presentation: {
      milestoneId: "growth-phase",
      milestoneLabel: "Growth and optimization underway",
    },
  },

  /* ── Recently completed (post-launch) ─────────────────────────── */
  {
    id: "recent-launch",
    kind: "delivery",
    status: "completed",
    label: "New Primal Motorsports platform launched",
    statement: "The new production website went live.",
    occurredAt: "2026-09-09",
    evidenceLabels: ["launch:2026-09-09"],
    evidenceStrength: "verified",
    briefingSection: "results",
  },
  {
    id: "recent-verification",
    kind: "delivery",
    status: "completed",
    label: "Production verification completed",
    statement: "Post-launch technical verification closed and retested.",
    occurredAt: "2026-09-11",
    evidenceLabels: ["verification:2026-09-11"],
    evidenceStrength: "verified",
    briefingSection: "results",
  },
  {
    id: "recent-redirects",
    kind: "delivery",
    status: "completed",
    label: "Protected legacy search URLs",
    statement: "Historical Primal URLs now route to the correct Racing School and Radical destinations.",
    occurredAt: "2026-09-11",
    evidenceLabels: ["seo:redirects"],
    evidenceStrength: "verified",
    briefingSection: "results",
  },
  {
    id: "recent-schema",
    kind: "delivery",
    status: "completed",
    label: "Completed business identity markup for Google",
    statement: "Public phone and postal information completed in LocalBusiness structured data.",
    occurredAt: "2026-09-11",
    evidenceLabels: ["seo:local-business"],
    evidenceStrength: "verified",
    briefingSection: "results",
  },
  {
    id: "recent-paid-organic",
    kind: "delivery",
    status: "completed",
    label: "Separated paid Racing School landing from organic indexing",
    statement: "Paid landing page indexing was separated while Google Ads functionality remained intact.",
    occurredAt: "2026-09-11",
    evidenceLabels: ["seo:paid-landing-noindex"],
    evidenceStrength: "verified",
    briefingSection: "results",
  },
  {
    id: "recent-lead-hardening",
    kind: "delivery",
    status: "completed",
    label: "Strengthened Service and Parts lead acceptance",
    statement: "Accepted inquiries now persist even if an email notification fails.",
    occurredAt: "2026-09-11",
    evidenceLabels: ["leads:service-parts-persist"],
    evidenceStrength: "verified",
    briefingSection: "results",
  },
  {
    id: "recent-media",
    kind: "delivery",
    status: "completed",
    label: "Optimized major SR3 production media",
    statement: "A major SR3 image was reduced from about 4.49 MB to about 444 KB at the same dimensions.",
    occurredAt: "2026-09-11",
    evidenceLabels: ["perf:sr3-image"],
    evidenceStrength: "verified",
    briefingSection: "results",
  },

  /* ── Journey beats ────────────────────────────────────────────── */
  {
    id: "story-strategy",
    kind: "milestone",
    status: "completed",
    label: "Website direction set together",
    statement: "Website strategy and direction were set together at the start of the rebuild.",
    occurredAt: null,
    evidenceLabels: ["story:strategy", "project:primal-motorsports"],
    evidenceStrength: "supported",
    briefingSection: "hidden",
    presentation: { storyBeatId: "story-strategy" },
  },
  {
    id: "story-ads",
    kind: "milestone",
    status: "completed",
    label: "Advertising launched with care",
    statement: "Advertising launched and continues under active refinement.",
    occurredAt: null,
    evidenceLabels: ["story:ads", "ads-audit:2026-08-12-to-2026-09-10"],
    evidenceStrength: "verified",
    briefingSection: "hidden",
    presentation: { storyBeatId: "story-ads" },
  },
  {
    id: "story-workspace",
    kind: "milestone",
    status: "completed",
    label: "Private workspace introduced",
    statement: "A private partnership workspace was introduced for leadership.",
    occurredAt: null,
    evidenceLabels: ["story:workspace", "phase-18c"],
    evidenceStrength: "verified",
    briefingSection: "hidden",
    presentation: { storyBeatId: "story-workspace" },
  },
  {
    id: "story-review",
    kind: "milestone",
    status: "completed",
    label: "Shared review rhythm established",
    statement: "Website Review established a shared refinement rhythm before launch.",
    occurredAt: null,
    evidenceLabels: ["story:review", "system:website-review"],
    evidenceStrength: "verified",
    briefingSection: "hidden",
    presentation: { storyBeatId: "story-review" },
  },
  {
    id: "story-prep",
    kind: "launch",
    status: "completed",
    label: "Launch preparation completed",
    statement: "Launch preparation completed ahead of the September 9 production go-live.",
    occurredAt: "2026-09-09",
    evidenceLabels: ["story:prep", "launch:2026-09-09"],
    evidenceStrength: "verified",
    briefingSection: "hidden",
    presentation: { storyBeatId: "story-prep" },
  },
  {
    id: "story-launch",
    kind: "launch",
    status: "completed",
    label: "Website live",
    statement: "The production website launched September 9, 2026.",
    briefingStatement:
      "Website launch is complete. The partnership focus is now measurable growth and optimization.",
    occurredAt: "2026-09-09",
    evidenceLabels: ["story:launch", "launch:2026-09-09"],
    evidenceStrength: "verified",
    briefingSection: "built",
    presentation: { storyBeatId: "story-launch" },
  },
  {
    id: "story-growth",
    kind: "milestone",
    status: "in-progress",
    label: "Growth and optimization",
    statement: "Qualified traffic, search visibility, and Ads efficiency are the active priorities.",
    occurredAt: "2026-09-11",
    evidenceLabels: ["story:growth", "plan:30-60-90"],
    evidenceStrength: "verified",
    briefingSection: "current",
    presentation: { storyBeatId: "story-growth" },
  },

  /* ── Connected reporting systems ──────────────────────────────── */
  {
    id: "search-console-connected",
    kind: "reporting",
    status: "completed",
    label: "Search Console connected",
    statement:
      "Search Console is connected. Live clicks, impressions, CTR, and position appear when ReportingFacts exist for the selected period.",
    occurredAt: null,
    evidenceLabels: ["provider:google-search-console", "facts:search"],
    evidenceStrength: "verified",
    briefingSection: "results",
  },
  {
    id: "historical-search-equity",
    kind: "seo",
    status: "completed",
    label: "Historical search equity documented",
    statement:
      "Historical primalracing.com Search Console data shows meaningful organic equity worth protecting — especially Racing School and Radical purchase-intent queries.",
    briefingStatement:
      "Recovered historical Search Console data (May 11 – December 31, 2025) documents prior organic equity. It is context for recovery priorities, not a complete old-versus-new business baseline.",
    occurredAt: "2026-09-11",
    evidenceLabels: ["gsc:primalracing.com:2025-05-11-to-2025-12-31", "leadership-report:historical"],
    evidenceStrength: "verified",
    briefingSection: "marketing",
  },
  {
    id: "executive-performance-introduced",
    kind: "reporting",
    status: "active",
    label: "Executive Performance introduced",
    statement: "Executive Performance is the calm leadership view of the partnership.",
    occurredAt: null,
    evidenceLabels: ["system:executive-performance"],
    evidenceStrength: "verified",
    briefingSection: "systems",
  },
  {
    id: "ga4-prepared",
    kind: "reporting",
    status: "active",
    label: "GA4 receiving production activity",
    statement:
      "GA4 property 549908814 is receiving production traffic. generate_lead and form_start are firing. The live Website panel stays separate until website-analytics sync is verified.",
    briefingStatement:
      "Website analytics are active in GA4. A verified recent snapshot and measurement notes are in the Leadership Report. Client-facing live Website metrics appear here only after entitlement + ReportingFacts sync.",
    occurredAt: "2026-09-11",
    evidenceLabels: [
      "ga4:property:549908814",
      "ga4:generate_lead",
      "entitlement:website-analytics:held",
      "provider:ga4:pipeline-ready",
      "leadership-report:ga4",
    ],
    evidenceStrength: "verified",
    briefingSection: "marketing",
  },

  /* ── Driver Portal — future only ──────────────────────────────── */
  {
    id: "platform-primal-os",
    kind: "platform",
    status: "planned",
    label: "Driver Portal direction",
    statement:
      "The live website and measurement foundation create a base for future operational and customer features, including the planned Driver Portal direction. That work is not delivered here.",
    occurredAt: null,
    evidenceLabels: [
      "case-study:primal-os-scoped",
      "platforms:motorsports-os",
      "repo:no-primal-os-implementation",
      "leadership-report:future-direction",
    ],
    evidenceStrength: "supported",
    briefingSection: "platform",
    platformOpportunity: {
      title: "Future direction",
      positioning:
        "The production website and measurement foundation create a base for future operational and customer functionality, including the planned Driver Portal direction.",
      capabilities: [
        "Driver Portal experiences",
        "Driver management",
        "Team operations",
        "Internal reporting",
      ],
      pricing: {
        mode: "prepared-separately",
        models: [
          { id: "implementation", label: "One-time implementation", amountLabel: null },
          { id: "monthly", label: "Monthly platform / support", amountLabel: null },
          {
            id: "bundle",
            label: "Implementation + monthly support",
            amountLabel: null,
          },
          { id: "phased", label: "Phased rollout", amountLabel: null },
          { id: "custom", label: "Custom scope", amountLabel: null },
        ],
        note: "Scope and pricing prepared separately when leadership is ready. Not part of the current engagement.",
      },
    },
  },

  /* ── Forward priorities (30 / 60 / 90) ─────────────────────────── */
  {
    id: "opportunity-lead-mgmt",
    kind: "opportunity",
    status: "planned",
    label: "Qualified lead measurement",
    statement:
      "Establish clean reporting of qualified website leads by program and source — separate from GA4 or Ads conversion counts.",
    occurredAt: null,
    evidenceLabels: ["plan:30-days", "leads:qualified"],
    evidenceStrength: "verified",
    priority: true,
    briefingSection: "next",
    presentation: { evolutionId: "lead-management" },
  },
  {
    id: "opportunity-exec-reporting",
    kind: "opportunity",
    status: "active",
    label: "Comparable performance reporting",
    statement:
      "Keep September 11 as the baseline and deliver comparable 30 / 60 / 90-day performance views.",
    occurredAt: null,
    evidenceLabels: ["plan:30-60-90", "baseline:2026-09-11"],
    evidenceStrength: "verified",
    priority: true,
    briefingSection: "next",
    presentation: { evolutionId: "executive-reporting" },
  },
  {
    id: "opportunity-search-recovery",
    kind: "opportunity",
    status: "planned",
    label: "Racing School and Radical search strength",
    statement:
      "Protect and strengthen high-value Racing School and Radical purchase-intent visibility using verified historical equity and the current baseline.",
    occurredAt: null,
    evidenceLabels: ["plan:30-days", "seo:racing-school", "seo:radical"],
    evidenceStrength: "verified",
    priority: true,
    briefingSection: "next",
    presentation: { evolutionId: "customer-journey" },
  },
  {
    id: "opportunity-expansion",
    kind: "opportunity",
    status: "planned",
    label: "Scale what converts",
    statement:
      "After clean measurement periods, expand channels and queries that produce qualified demand — and reduce wasted paid traffic.",
    occurredAt: null,
    evidenceLabels: ["plan:90-days", "ads:efficiency"],
    evidenceStrength: "verified",
    briefingSection: "next",
    presentation: { evolutionId: "expansion" },
  },
];
