import type { CollectionConfig } from "payload";
import { isPayloadAdminUser } from "../access/index.ts";
import { PAYLOAD_GROUPS } from "../admin/groups.ts";

export const ClientCalendarEvents: CollectionConfig = {
  slug: "client-calendar-events",
  labels: {
    singular: "Calendar event",
    plural: "Calendar events",
  },
  lockDocuments: false,
  timestamps: true,
  admin: {
    group: PAYLOAD_GROUPS.kxdOs,
    useAsTitle: "sourceTitle",
    defaultColumns: ["sourceTitle", "client", "startsOn", "status", "listedOnWebsite", "sourceSystem"],
    description:
      "Canonical client calendar events. Public website reads the public calendar API only.",
  },
  access: {
    read: isPayloadAdminUser,
    create: isPayloadAdminUser,
    update: isPayloadAdminUser,
    delete: isPayloadAdminUser,
  },
  fields: [
    {
      name: "client",
      type: "relationship",
      relationTo: "clients",
      required: true,
      index: true,
      admin: { position: "sidebar" },
    },
    { name: "eventKey", type: "text", required: true, index: true },
    { name: "titleOverride", type: "text" },
    { name: "sourceTitle", type: "text", required: true },
    { name: "summary", type: "textarea" },
    { name: "description", type: "textarea" },
    {
      name: "eventType",
      type: "select",
      required: true,
      defaultValue: "other",
      options: [
        { label: "Main event", value: "main_event" },
        { label: "Practice", value: "practice" },
        { label: "Test day", value: "test_day" },
        { label: "Prep", value: "prep" },
        { label: "School", value: "school" },
        { label: "Race", value: "race" },
        { label: "Briefing", value: "briefing" },
        { label: "Private", value: "private" },
        { label: "Support", value: "support" },
        { label: "Other", value: "other" },
      ],
    },
    { name: "sourceEventType", type: "text" },
    { name: "startsOn", type: "date", required: true, admin: { date: { pickerAppearance: "dayOnly" } } },
    { name: "endsOn", type: "date", admin: { date: { pickerAppearance: "dayOnly" } } },
    { name: "timezone", type: "text", defaultValue: "America/New_York" },
    { name: "allDay", type: "checkbox", defaultValue: true },
    {
      name: "status",
      type: "select",
      required: true,
      defaultValue: "draft",
      options: [
        { label: "Draft", value: "draft" },
        { label: "Scheduled", value: "scheduled" },
        { label: "Cancelled", value: "cancelled" },
        { label: "Postponed", value: "postponed" },
        { label: "Completed", value: "completed" },
      ],
    },
    { name: "listedOnWebsite", type: "checkbox", defaultValue: false },
    { name: "featured", type: "checkbox", defaultValue: false },
    {
      name: "location",
      type: "relationship",
      relationTo: "client-locations",
      admin: { description: "Owning Primal location/team — not the physical venue." },
    },
    { name: "venueName", type: "text" },
    { name: "venueCity", type: "text" },
    { name: "venueState", type: "text" },
    { name: "venueAddress", type: "text" },
    {
      name: "sourceSystem",
      type: "select",
      required: true,
      defaultValue: "manual",
      options: [
        { label: "Manual", value: "manual" },
        { label: "MotorsportReg", value: "motorsportreg" },
        { label: "Radical", value: "radical" },
        { label: "External", value: "external" },
      ],
    },
    { name: "sourceExternalId", type: "text", index: true },
    { name: "sourceUrl", type: "text" },
    { name: "sourceLastSyncedAt", type: "date" },
    {
      name: "sourcePresence",
      type: "select",
      defaultValue: "present",
      options: [
        { label: "Present", value: "present" },
        { label: "Missing from feed", value: "missing_from_feed" },
      ],
    },
    { name: "fieldAuthority", type: "json" },
    {
      name: "parentEvent",
      type: "relationship",
      relationTo: "client-calendar-events",
    },
    {
      name: "relationshipKind",
      type: "select",
      defaultValue: "none",
      options: [
        { label: "None", value: "none" },
        { label: "Practice", value: "practice" },
        { label: "Test day", value: "test_day" },
        { label: "Prep", value: "prep" },
        { label: "Briefing", value: "briefing" },
        { label: "Support", value: "support" },
        { label: "Related", value: "related" },
      ],
    },
    { name: "practiceNotes", type: "textarea" },
    { name: "registrationGuidance", type: "textarea" },
    { name: "activityLog", type: "json" },
    { name: "createdBy", type: "text" },
    { name: "updatedBy", type: "text" },
  ],
};
