import type { CollectionConfig } from "payload";
import { isAuthenticated } from "../access/index.ts";
import { PAYLOAD_GROUPS } from "../admin/groups.ts";

export const ExecutiveTimelineEvents: CollectionConfig = {
  slug: "executive-timeline-events",
  labels: { singular: "Executive Timeline Event", plural: "Executive Timeline Events" },
  defaultSort: "-occurredAt",
  lockDocuments: false,
  admin: {
    useAsTitle: "title",
    defaultColumns: [
      "client",
      "category",
      "importance",
      "sourceModule",
      "occurredAt",
      "pinned",
      "updatedAt",
    ],
    group: PAYLOAD_GROUPS.kxdOs,
    description:
      "Permanent relationship history — the single source of truth for every client. " +
      "Dashboard: /admin/operations/timeline",
  },
  access: {
    read: isAuthenticated,
    create: isAuthenticated,
    update: isAuthenticated,
    delete: isAuthenticated,
  },
  fields: [
    {
      name: "client",
      type: "relationship",
      relationTo: "clients",
      required: true,
      label: "Client",
      admin: { position: "sidebar" },
    },
    {
      name: "project",
      type: "relationship",
      relationTo: "client-projects",
      label: "Project",
      admin: { position: "sidebar" },
    },
    {
      name: "infrastructure",
      type: "relationship",
      relationTo: "client-infrastructure",
      label: "Infrastructure",
      admin: { position: "sidebar" },
    },
    {
      name: "request",
      type: "relationship",
      relationTo: "client-requests",
      label: "Request",
      admin: { position: "sidebar" },
    },
    {
      name: "deliverable",
      type: "relationship",
      relationTo: "monthly-deliverables",
      label: "Deliverable",
      admin: { position: "sidebar" },
    },
    {
      name: "category",
      type: "select",
      required: true,
      label: "Category",
      defaultValue: "relationship",
      options: [
        { label: "Relationship", value: "relationship" },
        { label: "Project", value: "project" },
        { label: "Creative", value: "creative" },
        { label: "Infrastructure", value: "infrastructure" },
        { label: "Website", value: "website" },
        { label: "SEO", value: "seo" },
        { label: "Analytics", value: "analytics" },
        { label: "Marketing", value: "marketing" },
        { label: "Finance", value: "finance" },
        { label: "Onboarding", value: "onboarding" },
        { label: "Meeting", value: "meeting" },
        { label: "Communication", value: "communication" },
        { label: "Support", value: "support" },
        { label: "Launch", value: "launch" },
        { label: "Growth", value: "growth" },
        { label: "System", value: "system" },
      ],
      admin: { position: "sidebar" },
    },
    {
      name: "importance",
      type: "select",
      required: true,
      label: "Importance",
      defaultValue: "normal",
      options: [
        { label: "Low", value: "low" },
        { label: "Normal", value: "normal" },
        { label: "High", value: "high" },
        { label: "Critical", value: "critical" },
      ],
      admin: { position: "sidebar" },
    },
    {
      name: "status",
      type: "select",
      label: "Status",
      defaultValue: "active",
      options: [
        { label: "Active", value: "active" },
        { label: "Open", value: "open" },
        { label: "Completed", value: "completed" },
        { label: "Archived", value: "archived" },
        { label: "Cancelled", value: "cancelled" },
      ],
      admin: { position: "sidebar" },
    },
    {
      name: "sourceModule",
      type: "select",
      required: true,
      label: "Source Module",
      defaultValue: "Manual",
      options: [
        { label: "Launch", value: "Launch" },
        { label: "Client HQ", value: "Client HQ" },
        { label: "Client Command", value: "Client Command" },
        { label: "Infrastructure", value: "Infrastructure" },
        { label: "Founder Intelligence", value: "Founder Intelligence" },
        { label: "Audits", value: "Audits" },
        { label: "Creative", value: "Creative" },
        { label: "Reels", value: "Reels" },
        { label: "Accounts", value: "Accounts" },
        { label: "Growth", value: "Growth" },
        { label: "Portal", value: "Portal" },
        { label: "Website Auditor", value: "Website Auditor" },
        { label: "Executive Notes", value: "Executive Notes" },
        { label: "Projects", value: "Projects" },
        { label: "Requests", value: "Requests" },
        { label: "Sales", value: "Sales" },
        { label: "Retainers", value: "Retainers" },
        { label: "Client Success", value: "Client Success" },
        { label: "Emails", value: "Emails" },
        { label: "Manual", value: "Manual" },
      ],
      admin: { position: "sidebar" },
    },
    {
      name: "pinned",
      type: "checkbox",
      label: "Pinned",
      defaultValue: false,
      admin: { position: "sidebar" },
    },
    {
      name: "internalOnly",
      type: "checkbox",
      label: "Internal Only",
      defaultValue: true,
      admin: {
        position: "sidebar",
        description: "Hidden from client-facing surfaces until published.",
      },
    },
    {
      type: "tabs",
      tabs: [
        {
          label: "Event",
          fields: [
            { name: "eventType", type: "text", required: true, label: "Event Type" },
            { name: "title", type: "text", required: true, label: "Title" },
            { name: "summary", type: "textarea", label: "Summary" },
            { name: "description", type: "textarea", label: "Description" },
            {
              name: "occurredAt",
              type: "date",
              required: true,
              label: "Occurred At",
              admin: { date: { pickerAppearance: "dayAndTime" } },
            },
            { name: "createdBy", type: "text", label: "Created By" },
            {
              name: "metadata",
              type: "json",
              label: "Metadata",
              admin: { description: "Structured context for integrations and future automation." },
            },
          ],
        },
      ],
    },
  ],
};
