import type { CollectionConfig } from "payload";
import { isAuthenticated } from "../access/index.ts";
import { PAYLOAD_GROUPS } from "../admin/groups.ts";

export const InfrastructureCosts: CollectionConfig = {
  slug: "infrastructure-costs",
  labels: { singular: "Infrastructure Cost", plural: "Infrastructure Costs" },
  defaultSort: "-updatedAt",
  lockDocuments: false,
  admin: {
    useAsTitle: "name",
    defaultColumns: [
      "client",
      "name",
      "category",
      "amount",
      "billingCycle",
      "paidBy",
      "active",
      "updatedAt",
    ],
    group: PAYLOAD_GROUPS.kxdOs,
    description: "Recurring and annual stack costs — domains, hosting, email, software, and tooling.",
  },
  access: {
    read: isAuthenticated,
    create: isAuthenticated,
    update: isAuthenticated,
    delete: isAuthenticated,
  },
  fields: [
    {
      name: "client",
      type: "relationship",
      relationTo: "clients",
      required: true,
      label: "Client",
      admin: { position: "sidebar" },
    },
    {
      name: "infrastructure",
      type: "relationship",
      relationTo: "client-infrastructure",
      label: "Infrastructure Record",
      admin: { position: "sidebar" },
    },
    { name: "name", type: "text", required: true, label: "Cost Name" },
    {
      name: "category",
      type: "select",
      required: true,
      label: "Category",
      defaultValue: "other",
      options: [
        { label: "Domain", value: "domain" },
        { label: "Hosting", value: "hosting" },
        { label: "Email", value: "email" },
        { label: "Analytics", value: "analytics" },
        { label: "Storage", value: "storage" },
        { label: "Software", value: "software" },
        { label: "Payments", value: "payments" },
        { label: "Automation", value: "automation" },
        { label: "AI", value: "ai" },
        { label: "Design", value: "design" },
        { label: "Other", value: "other" },
      ],
      admin: { position: "sidebar" },
    },
    { name: "vendor", type: "text", label: "Vendor" },
    {
      name: "amount",
      type: "number",
      required: true,
      label: "Amount ($)",
      min: 0,
    },
    {
      name: "billingCycle",
      type: "select",
      required: true,
      label: "Billing Cycle",
      defaultValue: "monthly",
      options: [
        { label: "Monthly", value: "monthly" },
        { label: "Annual", value: "annual" },
        { label: "One-Time", value: "one-time" },
      ],
      admin: { position: "sidebar" },
    },
    {
      name: "paidBy",
      type: "select",
      label: "Paid By",
      defaultValue: "unknown",
      options: [
        { label: "KXD", value: "kxd" },
        { label: "Client", value: "client" },
        { label: "Unknown", value: "unknown" },
      ],
      admin: { position: "sidebar" },
    },
    {
      name: "renewalDate",
      type: "date",
      label: "Renewal Date",
      admin: { date: { pickerAppearance: "dayOnly" } },
    },
    { name: "accountOwner", type: "text", label: "Account Owner" },
    { name: "notes", type: "textarea", label: "Notes" },
    {
      name: "active",
      type: "checkbox",
      label: "Active",
      defaultValue: true,
      admin: { position: "sidebar" },
    },
  ],
};
