import type { CollectionConfig } from "payload";
import { isAuthenticated } from "../access/index.ts";
import { PAYLOAD_GROUPS } from "../admin/groups.ts";

export const MonthlyReports: CollectionConfig = {
  slug: "monthly-reports",
  labels: { singular: "Monthly Report", plural: "Monthly Reports" },
  defaultSort: "-reportingYear,-reportingMonth",
  lockDocuments: false,
  admin: {
    useAsTitle: "title",
    defaultColumns: [
      "title",
      "client",
      "reportType",
      "reportingMonth",
      "reportingYear",
      "status",
      "accountHealthScore",
      "updatedAt",
    ],
    group: PAYLOAD_GROUPS.kxdOs,
    description: "Executive monthly reports — KXD Reporting Engine. Dashboard: /admin/operations/reports",
  },
  access: {
    read: isAuthenticated,
    create: isAuthenticated,
    update: isAuthenticated,
    delete: isAuthenticated,
  },
  fields: [
    {
      name: "title",
      type: "text",
      label: "Title",
      admin: { description: "Auto-generated if empty." },
    },
    {
      name: "status",
      type: "select",
      required: true,
      defaultValue: "draft",
      label: "Status",
      options: [
        { label: "Draft", value: "draft" },
        { label: "Generating", value: "generating" },
        { label: "Ready", value: "ready" },
        { label: "Sent", value: "sent" },
        { label: "Published", value: "published" },
        { label: "Archived", value: "archived" },
      ],
      admin: { position: "sidebar" },
    },
    {
      name: "reportType",
      type: "select",
      label: "Report Type",
      defaultValue: "monthly_marketing",
      options: [
        { label: "Google Ads", value: "google_ads" },
        { label: "SEO", value: "seo" },
        { label: "Website", value: "website" },
        { label: "Monthly Marketing", value: "monthly_marketing" },
        { label: "Analytics", value: "analytics" },
        { label: "Custom", value: "custom" },
      ],
      admin: { position: "sidebar" },
    },
    {
      name: "client",
      type: "relationship",
      relationTo: "clients",
      required: true,
      label: "Client",
      admin: { position: "sidebar" },
    },
    {
      name: "template",
      type: "relationship",
      relationTo: "report-templates",
      label: "Template",
      admin: { position: "sidebar" },
    },
    {
      name: "reportingMonth",
      type: "number",
      required: true,
      label: "Month",
      min: 1,
      max: 12,
      admin: { position: "sidebar" },
    },
    {
      name: "reportingYear",
      type: "number",
      required: true,
      label: "Year",
      admin: { position: "sidebar" },
    },
    {
      name: "periodStart",
      type: "date",
      label: "Period Start",
      admin: {
        position: "sidebar",
        date: { pickerAppearance: "dayOnly" },
        description: "Optional custom reporting period start.",
      },
    },
    {
      name: "periodEnd",
      type: "date",
      label: "Period End",
      admin: {
        position: "sidebar",
        date: { pickerAppearance: "dayOnly" },
        description: "Optional custom reporting period end.",
      },
    },
    {
      name: "accountHealthScore",
      type: "number",
      label: "Account Health Score",
      min: 0,
      max: 10,
      admin: {
        position: "sidebar",
        description: "Overall assessment score out of 10.",
        step: 0.1,
      },
    },
    {
      name: "version",
      type: "number",
      label: "Version",
      defaultValue: 1,
      admin: { position: "sidebar" },
    },
    {
      name: "preparedBy",
      type: "text",
      label: "Prepared By",
      admin: { position: "sidebar" },
    },
    {
      name: "approvedBy",
      type: "text",
      label: "Approved By",
      admin: { position: "sidebar" },
    },
    {
      name: "publishedAt",
      type: "date",
      label: "Published At",
      admin: { date: { pickerAppearance: "dayAndTime" }, position: "sidebar" },
    },
    {
      name: "viewCount",
      type: "number",
      label: "Portal Views",
      defaultValue: 0,
      admin: { readOnly: true, position: "sidebar" },
    },
    {
      type: "tabs",
      tabs: [
        {
          label: "Summary",
          fields: [
            { name: "executiveSummary", type: "textarea", label: "Executive Summary" },
            { name: "workCompleted", type: "textarea", label: "Work Completed" },
            { name: "notes", type: "textarea", label: "Notes" },
            { name: "nextMonthPriorities", type: "json", label: "Next Month Priorities" },
            {
              name: "clientFacingNotes",
              type: "textarea",
              label: "Client Notes",
              admin: { description: "Shown on the printable executive report." },
            },
            {
              name: "internalNotes",
              type: "textarea",
              label: "Internal Notes",
              admin: { description: "Internal only — never shown on the printable report." },
            },
          ],
        },
        {
          label: "Performance",
          fields: [
            {
              name: "campaignPerformance",
              type: "array",
              label: "Campaign Performance",
              fields: [
                { name: "campaignName", type: "text", required: true, label: "Campaign Name" },
                { name: "impressions", type: "number", label: "Impressions" },
                { name: "clicks", type: "number", label: "Clicks" },
                { name: "ctr", type: "number", label: "CTR (%)" },
                { name: "avgCpc", type: "number", label: "Avg CPC ($)" },
                { name: "cost", type: "number", label: "Cost ($)" },
                { name: "conversions", type: "number", label: "Conversions" },
                { name: "notes", type: "textarea", label: "Notes" },
              ],
            },
            {
              name: "geographicPerformance",
              type: "array",
              label: "Geographic Performance",
              fields: [
                { name: "location", type: "text", required: true, label: "Location" },
                { name: "impressions", type: "number", label: "Impressions" },
                { name: "clicks", type: "number", label: "Clicks" },
                { name: "ctr", type: "number", label: "CTR (%)" },
                { name: "avgCpc", type: "number", label: "Avg CPC ($)" },
                { name: "cost", type: "number", label: "Cost ($)" },
                { name: "conversions", type: "number", label: "Conversions" },
                { name: "notes", type: "textarea", label: "Notes" },
              ],
            },
            {
              name: "topSearchTerms",
              type: "array",
              label: "Top Search Terms",
              fields: [
                { name: "searchTerm", type: "text", required: true, label: "Search Term" },
                { name: "insight", type: "textarea", label: "Insight" },
                { name: "recommendation", type: "textarea", label: "Recommendation" },
              ],
            },
            {
              name: "optimizationWorkCompleted",
              type: "array",
              label: "Optimization Work Completed",
              fields: [
                { name: "title", type: "text", required: true, label: "Title" },
                { name: "description", type: "textarea", label: "Description" },
              ],
            },
            {
              name: "nextMonthStrategy",
              type: "array",
              label: "Next Month Strategy",
              fields: [
                { name: "title", type: "text", required: true, label: "Title" },
                {
                  name: "priority",
                  type: "select",
                  label: "Priority",
                  defaultValue: "medium",
                  options: [
                    { label: "Low", value: "low" },
                    { label: "Medium", value: "medium" },
                    { label: "High", value: "high" },
                  ],
                },
                { name: "description", type: "textarea", label: "Description" },
              ],
            },
          ],
        },
        {
          label: "Delivery",
          fields: [
            { name: "deliverables", type: "json", label: "Deliverables" },
            { name: "projects", type: "json", label: "Projects" },
            { name: "meetings", type: "json", label: "Meetings" },
          ],
        },
        {
          label: "Intelligence",
          fields: [
            { name: "websiteHealth", type: "json", label: "Website Health" },
            { name: "infrastructure", type: "json", label: "Infrastructure" },
            { name: "growth", type: "json", label: "Growth" },
            { name: "recommendations", type: "json", label: "Recommendations" },
            { name: "kpis", type: "json", label: "KPIs" },
          ],
        },
        {
          label: "Analytics",
          fields: [
            { name: "traffic", type: "json", label: "Traffic" },
            { name: "conversions", type: "json", label: "Conversions" },
            { name: "seo", type: "json", label: "SEO" },
            {
              name: "connectorStatus",
              type: "json",
              label: "Connector Status",
              admin: { description: "Future: GA4, GSC, Stripe, Clarity, etc." },
            },
          ],
        },
        {
          label: "Timeline",
          fields: [
            { name: "timeline", type: "json", label: "Timeline Events" },
          ],
        },
        {
          label: "Export",
          fields: [
            { name: "reportData", type: "json", label: "Full Report Snapshot" },
            { name: "htmlExport", type: "textarea", label: "HTML Export" },
            { name: "portalHtml", type: "textarea", label: "Portal HTML" },
          ],
        },
      ],
    },
  ],
};
