import type { CollectionConfig } from "payload";
import { isAuthenticated } from "../access/index.ts";
import { PAYLOAD_GROUPS } from "../admin/groups.ts";

export const SalesLeads: CollectionConfig = {
  slug: "sales-leads",
  labels: { singular: "Sales Lead", plural: "Sales Leads" },
  defaultSort: "-updatedAt",
  lockDocuments: false,
  admin: {
    useAsTitle: "companyName",
    defaultColumns: [
      "companyName",
      "contactName",
      "status",
      "estimatedValue",
      "probability",
      "nextFollowUp",
      "updatedAt",
    ],
    group: PAYLOAD_GROUPS.kxdOs,
    description: "KXD Sales Engine — pipeline leads. Dashboard: /admin/sales",
  },
  access: {
    read: isAuthenticated,
    create: isAuthenticated,
    update: isAuthenticated,
    delete: isAuthenticated,
  },
  fields: [
    {
      name: "status",
      type: "select",
      required: true,
      defaultValue: "new",
      label: "Pipeline Status",
      options: [
        { label: "New Leads", value: "new" },
        { label: "Needs Response", value: "discovery" },
        { label: "In Conversation", value: "nurturing" },
        { label: "Proposal / Decision", value: "proposal" },
        { label: "Decision (negotiation)", value: "negotiation" },
        { label: "Won", value: "won" },
        { label: "Not Moving", value: "lost" },
      ],
      admin: { position: "sidebar" },
    },
    {
      name: "source",
      type: "text",
      label: "Source",
      admin: { position: "sidebar" },
    },
    {
      name: "assignedTo",
      type: "text",
      label: "Assigned To",
      admin: { position: "sidebar" },
    },
    {
      name: "sourceResearchLead",
      type: "relationship",
      relationTo: "research-leads",
      label: "Source Research Lead",
      unique: true,
      admin: {
        position: "sidebar",
        description: "Original Junior Creator / Research Desk intake record.",
        readOnly: true,
      },
    },
    {
      name: "sourceInquiry",
      type: "relationship",
      relationTo: "inquiries",
      label: "Source Inquiry",
      unique: true,
      admin: {
        position: "sidebar",
        description: "Original /contact inquiry intake record.",
        readOnly: true,
      },
    },
    {
      name: "sourceProjectInquiry",
      type: "relationship",
      relationTo: "project-inquiries",
      label: "Source Project Inquiry",
      unique: true,
      admin: {
        position: "sidebar",
        description: "Original /start-project intake record.",
        readOnly: true,
      },
    },
    {
      name: "sourceWebsiteAudit",
      type: "relationship",
      relationTo: "website-audits",
      label: "Source Website Audit",
      unique: true,
      admin: {
        position: "sidebar",
        description: "Original Website Audit diagnostic lead.",
        readOnly: true,
      },
    },
    {
      name: "sourcedByJuniorCreator",
      type: "relationship",
      relationTo: "junior-creator-users",
      label: "Sourced By (Junior Creator)",
      admin: {
        position: "sidebar",
        description: "Attribution — survives promote → conversation → won.",
        readOnly: true,
      },
    },
    {
      name: "sourcedByName",
      type: "text",
      label: "Sourced By Name",
      admin: {
        position: "sidebar",
        description: "Denormalized researcher name for operator display.",
        readOnly: true,
      },
    },
    {
      name: "opportunityUrl",
      type: "text",
      label: "Opportunity URL",
      admin: {
        description: "Exact opportunity page URL. Never put email addresses here.",
      },
    },
    {
      name: "nextAction",
      type: "select",
      label: "Next Action",
      defaultValue: "none",
      options: [
        { label: "Respond today", value: "respond-today" },
        { label: "Follow up tomorrow", value: "follow-up-tomorrow" },
        { label: "Waiting on prospect", value: "waiting-on-prospect" },
        { label: "Send proposal", value: "send-proposal" },
        { label: "Review scope", value: "review-scope" },
        { label: "No action scheduled", value: "none" },
      ],
      admin: { position: "sidebar" },
    },
    {
      name: "nextActionNote",
      type: "text",
      label: "Next Action Note",
      admin: { position: "sidebar" },
    },
    {
      name: "lostReason",
      type: "select",
      label: "Lost Reason",
      options: [
        { label: "No response", value: "no-response" },
        { label: "Budget", value: "budget" },
        { label: "Timing", value: "timing" },
        { label: "Chose competitor", value: "chose-competitor" },
        { label: "Not a fit", value: "not-a-fit" },
        { label: "Project cancelled", value: "project-cancelled" },
        { label: "Other", value: "other" },
      ],
      admin: {
        position: "sidebar",
        description: "Required when moving an opportunity to Not Moving / Lost.",
      },
    },
    {
      name: "researchSubmittedAt",
      type: "date",
      label: "Original Research Submitted",
      admin: {
        position: "sidebar",
        readOnly: true,
        date: { pickerAppearance: "dayAndTime" },
      },
    },
    {
      type: "tabs",
      tabs: [
        {
          label: "Lead",
          fields: [
            { name: "companyName", type: "text", required: true, label: "Company / Prospect" },
            { name: "contactName", type: "text", required: true, label: "Contact Name" },
            { name: "email", type: "email", label: "Email" },
            { name: "phone", type: "text", label: "Phone" },
            { name: "website", type: "text", label: "Website" },
            { name: "industry", type: "text", label: "Industry" },
            {
              name: "tags",
              type: "text",
              label: "Tags",
              admin: { description: "Comma-separated tags." },
            },
            { name: "notes", type: "textarea", label: "Notes" },
          ],
        },
        {
          label: "Forecast",
          fields: [
            { name: "estimatedValue", type: "number", label: "Estimated Value ($)" },
            { name: "estimatedMRR", type: "number", label: "Estimated MRR ($)" },
            {
              name: "probability",
              type: "number",
              label: "Close Probability (%)",
              min: 0,
              max: 100,
              defaultValue: 25,
            },
            {
              name: "nextFollowUp",
              type: "date",
              label: "Next Follow-Up",
              admin: { date: { pickerAppearance: "dayAndTime" } },
            },
          ],
        },
      ],
    },
  ],
};
